"""Additional curated business models (70), merged into the database by data_loader.

Same fields as data_loader.BusinessModel. Competitors are compact tuples:
(name, url, note, is_local). Revenue figures are only filled in where a public,
founder-reported number exists; otherwise mrr_usd is None and revenue_note names
the companies that proved the model.
"""

DEV = "Dev & Productivity Tools"
MKT = "Marketing & Growth"
ECOM = "E-commerce Add-ons"
CRE = "Creator Economy"
LOC = "Local Services"
AI = "AI Tools"
FIN = "Finance & Admin"
HOS = "Hospitality & Gastro"
COM = "Communities & Marketplaces"

MORE_MODELS: list[dict] = [
    # ------------------------------------------------------------------ Dev & Productivity
    dict(
        name="Cookie Consent Manager (Cookiebot archetype)", url="https://www.cookiebot.com", category=DEV,
        niche="Cookie scanning & consent banners", revenue_model="Subscription per domain",
        revenue_note="Cookiebot (now Usercentrics) and CookieYes grew large on this model",
        problem="Websites must collect opt-in consent before analytics/ads cookies and prove it on audit.",
        tech_stack=["JavaScript SDK", "Headless crawler", "Node.js"],
        price_usd=12, cz_sam=80_000, demand=4, competition=4, complexity=3, regulatory=2, moat=3,
        cz_segments=["Czech SMB websites", "WordPress/Shoptet agencies", "Municipal websites"],
        cz_competitors=[("Cookiebot / Usercentrics", "https://www.cookiebot.com", "Market leader", False),
                        ("CookieYes", "https://www.cookieyes.com", "Cheap, popular with WordPress", False),
                        ("Shoptet built-in cookie bar", "https://www.shoptet.cz", "Covers basic e-shop needs", True)],
        cz_notes="Czech cookie rules switched to opt-in in 2022; Czech-language banners and ÚOOÚ-aligned defaults matter.",
    ),
    dict(
        name="GDPR & Legal Docs Generator (iubenda archetype)", url="https://www.iubenda.com", category=DEV,
        niche="Auto-generated privacy policies, terms and consent logs", revenue_model="Annual subscription",
        revenue_note="iubenda scaled to a large bootstrapped-origin business in Italy",
        problem="Small businesses can't afford lawyers to draft and update privacy policies and terms.",
        tech_stack=["Rails", "Template engine", "Embed widgets"],
        price_usd=10, cz_sam=60_000, demand=3, competition=3, complexity=3, regulatory=3, moat=4,
        cz_segments=["E-shops needing VOP & reklamační řád", "OSVČ websites", "Web agencies"],
        cz_competitors=[("Legito", "https://www.legito.com", "Prague legal document automation", True),
                        ("Law-firm templates", "", "One-off, not kept up to date", True),
                        ("iubenda", "https://www.iubenda.com", "No Czech consumer-law specifics", False)],
        cz_notes="Czech e-shops need VOP, reklamační řád and 14-day withdrawal forms - templates must follow the Civil Code.",
    ),
    dict(
        name="E-signature with Bank Identity (DocuSign archetype)", url="https://www.docusign.com", category=DEV,
        niche="Electronic signatures & document workflows", revenue_model="Subscription per user + envelope packs",
        revenue_note="DocuSign proved the category; SignWell/Documenso show bootstrapped niches",
        problem="Contracts still get printed, signed and scanned; identity of the signer is uncertain.",
        tech_stack=["Next.js", "PDF signing (PAdES)", "Bank iD API"],
        price_usd=20, cz_sam=40_000, demand=3, competition=4, complexity=4, regulatory=3, moat=4,
        cz_segments=["Real-estate agencies", "HR departments", "Small law & accounting firms"],
        cz_competitors=[("Signi", "https://www.signi.com", "Czech e-signature platform", True),
                        ("DocuSign / Adobe Sign", "", "Enterprise standard", False)],
        cz_notes="Czech Bankovní identita (Bank iD) enables strong signer identification - a genuine local wedge.",
    ),
    dict(
        name="Web Accessibility Checker (EAA compliance)", url="https://www.silktide.com", category=DEV,
        niche="Automated accessibility audits & fix reports", revenue_model="Subscription per site",
        revenue_note="Silktide, Siteimprove and accessiBe prove willingness to pay",
        problem="The European Accessibility Act now requires many e-shops and services to be accessible.",
        tech_stack=["Headless Chrome", "axe-core", "Python"],
        price_usd=40, cz_sam=15_000, demand=4, competition=2, complexity=3, regulatory=2, moat=3,
        cz_segments=["Mid-size e-shops", "Banks & insurers' vendors", "Web agencies"],
        cz_competitors=[("Global audit tools (Siteimprove, Silktide)", "", "English-first, enterprise pricing", False),
                        ("Accessibility consultancies", "", "Manual audits, expensive", True)],
        cz_notes="EAA obligations apply since June 2025; micro-enterprises offering services are largely exempt - verify the Czech transposition.",
    ),
    dict(
        name="Website Translation Layer (Weglot archetype)", url="https://www.weglot.com", category=DEV,
        niche="One-click multilingual websites & e-shops", revenue_model="Subscription by word count",
        revenue_note="Weglot (France) grew bootstrapped to a multi-million ARR business",
        problem="Expanding to new markets needs translated sites with SEO-friendly URLs.",
        tech_stack=["JavaScript proxy", "Machine translation APIs", "CDN"],
        price_usd=29, cz_sam=12_000, demand=4, competition=3, complexity=4, regulatory=1, moat=3,
        cz_segments=["Czech e-shops expanding to SK/PL/HU/DE", "Hotels", "B2B manufacturers"],
        cz_competitors=[("Weglot", "https://www.weglot.com", "Global leader", False),
                        ("Shoptet multi-language projects", "https://www.shoptet.cz", "Native but manual", True),
                        ("Translation agencies", "", "Human quality, slow", True)],
        cz_notes="Czech e-commerce is highly export-oriented (Slovakia first); pair with Heureka.sk/Árukereső feed support.",
    ),
    dict(
        name="Agency Time Tracking & Profitability (Toggl archetype)", url="https://toggl.com", category=DEV,
        niche="Time tracking tied to budgets and invoicing", revenue_model="Subscription per user",
        revenue_note="Toggl (Estonia) is a long-running profitable example",
        problem="Agencies don't know which clients and projects actually make money.",
        tech_stack=["React", "Go", "PostgreSQL"],
        price_usd=10, cz_sam=8_000, demand=3, competition=4, complexity=3, regulatory=1, moat=2,
        cz_segments=["Digital & design agencies", "IT consultancies", "Architecture studios"],
        cz_competitors=[("Costlocker", "https://www.costlocker.com", "Czech agency profitability tool", True),
                        ("Clockify", "https://clockify.me", "Free tier", False),
                        ("Toggl Track", "https://toggl.com", "", False)],
    ),
    dict(
        name="Shift Scheduling for Hourly Staff (Deputy archetype)", url="https://www.deputy.com", category=DEV,
        niche="Rotas, availability, attendance & DPP/DPČ tracking", revenue_model="Subscription per employee",
        revenue_note="Deputy, When I Work and Homebase built large businesses on SMB shift work",
        problem="Gastro and retail managers plan shifts in Excel and WhatsApp, and lose track of hour limits.",
        tech_stack=["React Native", "Node.js", "PostgreSQL"],
        price_usd=3, price_czk_override=990, cz_sam=25_000, demand=4, competition=2, complexity=3, regulatory=3, moat=4,
        cz_segments=["Restaurants & cafés", "Retail chains with 5-50 staff", "Hotels"],
        cz_competitors=[("Excel / WhatsApp", "", "Status quo", True),
                        ("POS attendance modules", "", "Basic clock-in only (verify features)", True),
                        ("Deputy / When I Work", "", "No Czech labour-law logic", False)],
        cz_notes="Price is per venue. DPP hour caps and mandatory DPP reporting to ČSSZ (since 2024 - verify) are a strong local hook.",
    ),
    dict(
        name="Instatus", url="https://instatus.com", category=DEV,
        niche="Hosted status pages & incident communication", revenue_model="Subscription SaaS",
        revenue_note="Bootstrapped alternative to Atlassian Statuspage; revenue not public",
        problem="SaaS companies need a fast, cheap way to communicate outages.",
        tech_stack=["Next.js", "Static hosting", "Uptime integrations"],
        price_usd=20, cz_sam=1_500, demand=2, competition=4, complexity=2, regulatory=1, moat=1,
        cz_segments=["Czech SaaS startups", "Hosting providers", "Fintechs"],
        cz_competitors=[("Atlassian Statuspage", "https://www.atlassian.com/software/statuspage", "", False),
                        ("Better Stack status pages", "", "Bundled with monitoring", False)],
        cz_notes="Global product - Czech market alone is tiny.",
    ),

    # ------------------------------------------------------------------ Marketing & Growth
    dict(
        name="Kit (formerly ConvertKit)", url="https://kit.com", category=MKT,
        niche="Email marketing for creators", revenue_model="Subscription by subscriber count",
        mrr_usd=3_000_000, revenue_note="Public revenue dashboard showed ~$35-40M ARR; approximate",
        problem="Creators need simple email automation to sell products to their audience.",
        tech_stack=["Ruby on Rails", "MySQL", "Sidekiq"],
        price_usd=29, cz_sam=15_000, demand=3, competition=5, complexity=4, regulatory=2, moat=2,
        cz_segments=["Czech creators & coaches", "Small e-shops", "Newsletter writers"],
        cz_competitors=[("Ecomail", "https://ecomail.cz", "Czech email marketing", True),
                        ("SmartEmailing", "https://www.smartemailing.cz", "Czech marketing automation", True),
                        ("MailerLite", "https://www.mailerlite.com", "Lithuanian, localised & cheap", False)],
    ),
    dict(
        name="Buffer", url="https://buffer.com", category=MKT,
        niche="Social media scheduling for small teams", revenue_model="Subscription per channel",
        mrr_usd=1_600_000, revenue_note="Buffer publishes revenue openly; ~$20M ARR, approximate",
        problem="Small businesses struggle to post consistently across social networks.",
        tech_stack=["Node.js", "React", "MongoDB"],
        price_usd=6, cz_sam=30_000, demand=3, competition=5, complexity=3, regulatory=1, moat=1,
        cz_segments=["Small businesses", "Marketing freelancers", "Agencies"],
        cz_competitors=[("Meta Business Suite", "", "Free scheduler for FB/IG", False),
                        ("Buffer / Hootsuite", "", "Already used in CZ", False)],
    ),
    dict(
        name="Review Request Automation (NiceJob archetype)", url="https://get.nicejob.com", category=MKT,
        niche="Automated SMS/email review requests for local businesses", revenue_model="Subscription SaaS",
        revenue_note="NiceJob, Podium and Birdeye prove local businesses pay for reviews",
        problem="Happy customers rarely leave reviews unless asked at the right moment.",
        tech_stack=["Node.js", "SMS gateway", "Google Business Profile API"],
        price_usd=49, cz_sam=40_000, demand=4, competition=2, complexity=2, regulatory=2, moat=4,
        cz_segments=["Car services & tyre shops", "Dentists & clinics", "Trades & craftsmen"],
        cz_competitors=[("Firmy.cz reviews", "https://www.firmy.cz", "Seznam's directory - key review surface", True),
                        ("Google reviews (manual asks)", "", "Status quo", False),
                        ("Podium / Birdeye", "", "US-only focus", False)],
        cz_notes="Czech twist: collect reviews on both Google AND Firmy.cz (Seznam), which foreign tools ignore.",
    ),
    dict(
        name="Local SEO for Google & Seznam (BrightLocal archetype)", url="https://www.brightlocal.com",
        category=MKT, niche="Listings management, rank tracking & citation audits", revenue_model="Subscription SaaS",
        revenue_note="BrightLocal (UK) grew bootstrapped serving local-SEO agencies",
        problem="Local businesses have inconsistent listings and don't know how they rank in their neighbourhood.",
        tech_stack=["Python", "SERP scraping", "Maps APIs"],
        price_usd=39, cz_sam=6_000, demand=3, competition=3, complexity=3, regulatory=1, moat=5,
        cz_segments=["Local-SEO agencies", "Franchise & multi-location businesses", "Clinics"],
        cz_competitors=[("Collabim", "https://www.collabim.cz", "Czech SEO rank tracking", True),
                        ("Marketing Miner", "https://www.marketingminer.com", "Czech SEO data tool", True),
                        ("BrightLocal", "https://www.brightlocal.com", "No Seznam/Firmy.cz support", False)],
        cz_notes="Seznam still has meaningful search share in CZ - tracking Seznam + Firmy.cz is a real moat.",
    ),
    dict(
        name="Sklik + Google Ads Client Reporting (AgencyAnalytics archetype)", url="https://agencyanalytics.com",
        category=MKT, niche="White-label marketing dashboards for agencies", revenue_model="Subscription per client",
        revenue_note="AgencyAnalytics grew to a large SaaS serving small agencies",
        problem="Agencies waste hours every month building client reports from many ad platforms.",
        tech_stack=["Python", "Ad platform APIs", "React dashboards"],
        price_usd=59, cz_sam=3_000, demand=4, competition=3, complexity=3, regulatory=1, moat=5,
        cz_segments=["PPC agencies", "Freelance PPC specialists", "In-house e-commerce teams"],
        cz_competitors=[("Looker Studio + connectors", "", "Free but fiddly; few Sklik connectors", False),
                        ("Marketing Miner", "https://www.marketingminer.com", "SEO-focused", True),
                        ("AgencyAnalytics", "https://agencyanalytics.com", "No Sklik integration", False)],
        cz_notes="Seznam Sklik is a must-have ad channel in CZ that global reporting tools rarely support.",
    ),
    dict(
        name="Influencer Marketplace (Collabstr archetype)", url="https://collabstr.com", category=MKT,
        niche="Book micro-influencers with fixed-price packages", revenue_model="Commission on bookings",
        revenue_note="Collabstr grew as a bootstrapped marketplace",
        problem="Small brands can't find and pay trustworthy micro-influencers easily.",
        tech_stack=["Next.js", "Stripe Connect", "Instagram/TikTok APIs"],
        price_usd=60, price_czk_override=900, cz_sam=8_000, demand=3, competition=3, complexity=3, regulatory=2, moat=3,
        cz_segments=["Shoptet D2C brands", "Restaurants & cafés", "Local services"],
        cz_competitors=[("Czech influencer agencies", "", "Full-service, expensive", True),
                        ("Direct Instagram DMs", "", "Status quo", True)],
        cz_notes="Price = commission per booking-month per active brand. Czech ad-disclosure rules apply to paid posts.",
    ),
    dict(
        name="AI SEO Content Writer in Czech (Surfer archetype)", url="https://surferseo.com", category=MKT,
        niche="SEO-optimised articles and briefs", revenue_model="Subscription SaaS",
        revenue_note="Surfer and Jasper proved demand; many bootstrapped clones exist",
        problem="Writing SEO content that ranks is slow and expensive.",
        tech_stack=["Python", "LLM APIs", "SERP data"],
        price_usd=49, cz_sam=10_000, demand=3, competition=3, complexity=3, regulatory=1, moat=3,
        cz_segments=["E-shop blogs", "SEO agencies", "Affiliate site owners"],
        cz_competitors=[("Collabim / Marketing Miner", "", "Czech SEO data, not writing", True),
                        ("Surfer / Jasper / ChatGPT", "", "Weaker Czech SERP & morphology", False)],
        cz_notes="Czech morphology (declension) makes keyword matching harder - a real quality advantage for a local tool.",
    ),

    # ------------------------------------------------------------------ E-commerce Add-ons
    dict(
        name="Product Feed Manager (DataFeedWatch archetype)", url="https://www.datafeedwatch.com", category=ECOM,
        niche="Optimise product feeds for comparison sites & ads", revenue_model="Subscription by product count",
        revenue_note="DataFeedWatch and Channable built large businesses on feed optimisation",
        problem="E-shops lose visibility when product feeds are messy or mapped to the wrong categories.",
        tech_stack=["Python", "XML/CSV pipelines", "Shop APIs"],
        price_usd=39, cz_sam=20_000, demand=4, competition=4, complexity=3, regulatory=1, moat=4,
        cz_segments=["Shoptet & Upgates merchants", "PPC agencies", "Marketplace sellers"],
        cz_competitors=[("Mergado", "https://www.mergado.com", "Brno-based feed-management leader", True),
                        ("Channable / DataFeedWatch", "", "Weaker Heureka/Zboží support", False)],
        cz_notes="Heureka and Zboží.cz feed specs are Czech-specific; Mergado dominates, so a niche angle is required.",
    ),
    dict(
        name="Post-purchase Upsell App (ReConvert archetype)", url="https://www.reconvert.io", category=ECOM,
        niche="Thank-you page upsells & one-click add-ons", revenue_model="App subscription by order volume",
        revenue_note="ReConvert and similar Shopify apps report multi-million ARR",
        problem="E-shops leave money on the table after checkout.",
        tech_stack=["Node.js", "Shop platform API", "React widgets"],
        price_usd=15, cz_sam=40_000, demand=3, competition=3, complexity=2, regulatory=1, moat=3,
        cz_segments=["Shoptet merchants", "Cosmetics & supplements e-shops", "Fashion e-shops"],
        cz_competitors=[("Shoptet Addons marketplace", "https://doplnky.shoptet.cz", "Check existing upsell add-ons", True)],
    ),
    dict(
        name="Subscriptions for E-shops (Recharge archetype)", url="https://rechargepayments.com", category=ECOM,
        niche="Recurring orders for consumables", revenue_model="Subscription + % of subscription revenue",
        revenue_note="Recharge became a very large Shopify ecosystem company",
        problem="Coffee, pet food and supplement shops want repeat revenue without manual reorders.",
        tech_stack=["Node.js", "Recurring card payments", "Shop API"],
        price_usd=39, cz_sam=8_000, demand=3, competition=2, complexity=4, regulatory=2, moat=3,
        cz_segments=["Coffee roasters", "Pet food & supplement e-shops", "Cosmetics brands"],
        cz_competitors=[("Shoptet / Upgates native options", "", "Limited recurring support (verify)", True),
                        ("Payment-gateway recurring APIs (Comgate, GoPay)", "", "Building blocks only", True)],
    ),
    dict(
        name="Returns & Complaints Portal (Loop Returns archetype)", url="https://www.loopreturns.com", category=ECOM,
        niche="Self-service returns, exchanges and reklamace", revenue_model="Subscription by return volume",
        revenue_note="Loop, ReturnGO and AfterShip proved the category",
        problem="Returns and warranty claims are handled by email and spreadsheets.",
        tech_stack=["Next.js", "Carrier APIs", "Shop API"],
        price_usd=49, cz_sam=15_000, demand=4, competition=4, complexity=3, regulatory=2, moat=3,
        cz_segments=["Fashion e-shops", "Electronics e-shops", "Marketplace sellers"],
        cz_competitors=[("Retino", "https://www.retino.com", "Czech returns & claims app", True),
                        ("Packeta return labels", "https://www.packeta.com", "Logistics only", True)],
        cz_notes="Czech consumers have a 14-day withdrawal right and 2-year warranty claims (reklamace) with deadlines.",
    ),
    dict(
        name="Shipping Label & Carrier Hub (ShipStation archetype)", url="https://www.shipstation.com", category=ECOM,
        niche="Multi-carrier labels, tracking & pickup points", revenue_model="Subscription by shipment volume",
        revenue_note="ShipStation was acquired after reaching large scale",
        problem="Small e-shops copy addresses between carrier portals by hand.",
        tech_stack=["PHP/Node.js", "Carrier APIs", "Label printing"],
        price_usd=25, cz_sam=30_000, demand=3, competition=5, complexity=3, regulatory=1, moat=2,
        cz_segments=["Small e-shops", "Etsy/Vinted power sellers", "Wholesalers"],
        cz_competitors=[("Balíkobot", "https://www.balikobot.cz", "Czech multi-carrier API", True),
                        ("Packeta (Zásilkovna)", "https://www.packeta.com", "Dominant pickup-point network", True),
                        ("Shoptet carrier integrations", "", "Native", True)],
    ),
    dict(
        name="Marketplace Connector: Allegro, Kaufland, eMAG (ChannelEngine archetype)",
        url="https://www.channelengine.com", category=ECOM,
        niche="List products and sync orders across marketplaces", revenue_model="Subscription + order fees",
        revenue_note="ChannelEngine and BaseLinker grew fast on multi-marketplace selling",
        problem="Czech sellers want to expand to marketplaces but managing stock and orders across them is painful.",
        tech_stack=["Python", "Marketplace APIs", "Queue workers"],
        price_usd=59, cz_sam=10_000, demand=4, competition=4, complexity=4, regulatory=1, moat=3,
        cz_segments=["Shoptet merchants going cross-border", "Brands selling on Allegro.cz / Kaufland.cz", "Wholesalers"],
        cz_competitors=[("BaseLinker", "https://base.com", "Polish, very popular in CEE", False),
                        ("Mergado", "https://www.mergado.com", "Feeds + marketplace tools", True),
                        ("ChannelEngine", "https://www.channelengine.com", "Enterprise focus", False)],
        cz_notes="Allegro entered CZ via its Mall Group acquisition; Kaufland.cz runs a growing marketplace.",
    ),
    dict(
        name="Competitor Price Monitoring (Prisync archetype)", url="https://prisync.com", category=ECOM,
        niche="Track competitor prices & stock, suggest repricing", revenue_model="Subscription by SKU count",
        revenue_note="Prisync and Price2Spy are long-running profitable niche SaaS",
        problem="E-shops lose sales on comparison sites when they're not priced competitively.",
        tech_stack=["Python", "Scrapers", "Heureka/Zboží data"],
        price_usd=59, cz_sam=8_000, demand=3, competition=3, complexity=3, regulatory=1, moat=3,
        cz_segments=["Electronics e-shops", "Sports & hobby e-shops", "Brand manufacturers (MAP monitoring)"],
        cz_competitors=[("Heureka merchant analytics", "https://www.heureka.cz", "Price position on Heureka", True),
                        ("Czech price-monitoring tools", "", "Several exist - verify", True),
                        ("Prisync / Price2Spy", "", "", False)],
    ),
    dict(
        name="Gift Cards & Vouchers for E-shops (Rise.ai archetype)", url="https://rise.ai", category=ECOM,
        niche="Digital gift cards, store credit & vouchers", revenue_model="App subscription",
        revenue_note="Rise.ai and similar Shopify apps proved the model",
        problem="Shops can't easily sell gift vouchers or issue store credit instead of refunds.",
        tech_stack=["Node.js", "Shop API", "PDF/email vouchers"],
        price_usd=20, cz_sam=30_000, demand=3, competition=2, complexity=2, regulatory=2, moat=3,
        cz_segments=["Shoptet merchants", "Restaurants & spas (dárkové poukazy)", "Experience providers"],
        cz_competitors=[("Shoptet voucher features", "https://www.shoptet.cz", "Basic native discount codes", True),
                        ("Printed vouchers", "", "Status quo for local businesses", True)],
        cz_notes="Gift vouchers are a big Christmas business in CZ; watch VAT treatment of single- vs. multi-purpose vouchers.",
    ),
    dict(
        name="B2B Wholesale Portal for Small Brands (Faire/SparkLayer archetype)", url="https://www.sparklayer.io",
        category=ECOM, niche="Wholesale ordering portal with customer-specific prices", revenue_model="Subscription SaaS",
        revenue_note="Faire proved demand; SparkLayer and Handshake serve brand-owned B2B portals",
        problem="Small brands take wholesale orders from shops by email and Excel price lists.",
        tech_stack=["Next.js", "ERP/accounting integrations"],
        price_usd=79, cz_sam=5_000, demand=3, competition=3, complexity=3, regulatory=1, moat=3,
        cz_segments=["Czech food & drink producers", "Cosmetics brands", "Fashion & design brands"],
        cz_competitors=[("Shoptet / Upgates B2B modules", "", "Platform-native options", True),
                        ("Excel price lists + email", "", "Status quo", True)],
    ),

    # ------------------------------------------------------------------ Creator Economy
    dict(
        name="Paid Memberships for Creators (Patreon archetype)", url="https://www.patreon.com", category=CRE,
        niche="Recurring fan support & paid content", revenue_model="Commission on creator revenue",
        revenue_note="Patreon/Substack proved the model; Czech local players already exist",
        problem="Creators want recurring income from their most loyal fans.",
        tech_stack=["Next.js", "Payment gateway", "Content hosting"],
        price_usd=50, price_czk_override=600, cz_sam=6_000, demand=3, competition=5, complexity=3, regulatory=2, moat=2,
        cz_segments=["YouTubers & podcasters", "Journalists & newsletter writers", "Artists"],
        cz_competitors=[("HeroHero", "https://herohero.co", "Czech creator membership platform", True),
                        ("Forendors", "https://www.forendors.cz", "Czech creator support platform", True),
                        ("Patreon", "https://www.patreon.com", "", False)],
        cz_notes="Price = platform commission per active creator per month. Local market already has two strong players.",
    ),
    dict(
        name="Digital Product Storefront (Gumroad archetype)", url="https://gumroad.com", category=CRE,
        niche="Sell e-books, templates and presets with instant delivery", revenue_model="Transaction fee",
        revenue_note="Gumroad publishes open metrics; payouts in the hundreds of $M range",
        problem="Creators need to sell digital files without building an e-shop or handling EU VAT.",
        tech_stack=["Rails", "Stripe", "CDN"],
        price_usd=20, price_czk_override=350, cz_sam=12_000, demand=3, competition=3, complexity=2, regulatory=3, moat=3,
        cz_segments=["Designers selling templates", "Fitness & nutrition coaches", "Photographers"],
        cz_competitors=[("Mioweb", "https://www.mioweb.cz", "Czech builder with digital-sales features", True),
                        ("Gumroad / Payhip", "", "No Czech invoicing", False)],
        cz_notes="Monthly figure is fees per active seller. Must handle EU VAT OSS and Czech invoices (IČO/DIČ).",
    ),
    dict(
        name="Paid Community Platform (Skool archetype)", url="https://www.skool.com", category=CRE,
        niche="Community + courses + gamification in one place", revenue_model="Flat monthly subscription",
        revenue_note="Skool and Circle grew rapidly; figures not officially disclosed",
        problem="Facebook groups are noisy and hard to monetise.",
        tech_stack=["Go/React", "Video hosting", "Stripe"],
        price_usd=99, cz_sam=4_000, demand=2, competition=4, complexity=3, regulatory=1, moat=2,
        cz_segments=["Czech coaches & course creators", "Professional associations", "Hobby communities"],
        cz_competitors=[("Facebook groups", "", "Free default", False),
                        ("Skool / Circle", "", "English-only UI", False)],
    ),
    dict(
        name="Czech Transcription & Subtitles (Descript/Rev archetype)", url="https://www.rev.com", category=CRE,
        niche="Accurate Czech speech-to-text, subtitles and meeting notes", revenue_model="Subscription + per-minute",
        revenue_note="Rev and Otter prove large demand in English",
        problem="Czech transcription from global tools needs heavy manual correction.",
        tech_stack=["Python", "Whisper / Czech ASR models", "Editor UI"],
        price_usd=20, cz_sam=15_000, demand=3, competition=4, complexity=4, regulatory=2, moat=4,
        cogs_pct=0.15,
        cz_segments=["Podcasters & YouTubers", "Journalists", "Universities & courts"],
        cz_competitors=[("Beey (Newton Technologies)", "https://www.beey.io", "Czech transcription leader", True),
                        ("Otter / Descript", "", "Weak Czech support", False)],
    ),
    dict(
        name="Event Ticketing for Small Organisers (Eventbrite archetype)", url="https://www.eventbrite.com",
        category=CRE, niche="Tickets, check-in and payouts for workshops & events", revenue_model="Per-ticket fee",
        revenue_note="Eventbrite is public; many niche ticketing tools are bootstrapped",
        problem="Small organisers need ticketing without big platform fees.",
        tech_stack=["Next.js", "Payment gateway", "QR check-in app"],
        price_usd=30, price_czk_override=500, cz_sam=10_000, demand=3, competition=5, complexity=3, regulatory=2, moat=2,
        cz_segments=["Workshop organisers", "Clubs & small venues", "Conferences"],
        cz_competitors=[("GoOut", "https://goout.net", "Czech event discovery & ticketing", True),
                        ("Smsticket / Ticketportal", "", "Established Czech ticketing", True),
                        ("Eventbrite", "https://www.eventbrite.com", "", False)],
        cz_notes="Monthly figure = fees per active organiser.",
    ),

    dict(
        name="Client Galleries for Photographers (Pixieset archetype)", url="https://pixieset.com", category=CRE,
        niche="Online photo delivery, proofing and print sales", revenue_model="Subscription by storage",
        revenue_note="Pixieset grew bootstrapped to a large business serving photographers",
        problem="Photographers deliver photos via WeTransfer links with no branding, proofing or upsells.",
        tech_stack=["Next.js", "Object storage + CDN", "Print-lab integrations"],
        price_usd=20, cz_sam=8_000, demand=3, competition=3, complexity=3, regulatory=1, moat=2,
        cz_segments=["Wedding photographers", "Family & newborn photographers", "Event photographers"],
        cz_competitors=[("WeTransfer / Google Drive", "", "Free status quo", False),
                        ("Pixieset / Pic-Time", "", "English UI, no Czech print labs", False)],
        cz_notes="Integrate Czech print labs and CZK invoicing; weddings are seasonal (May-September).",
    ),

    # ------------------------------------------------------------------ AI Tools
    dict(
        name="AI Phone Receptionist in Czech (Smith.ai archetype)", url="https://smith.ai", category=AI,
        niche="AI voice agent that answers calls, books appointments and takes messages",
        revenue_model="Subscription + per-call", revenue_note="Smith.ai and a wave of AI-voice startups prove demand",
        problem="Small businesses miss calls while working; missed calls are lost customers.",
        tech_stack=["Telephony (SIP/Twilio)", "Speech-to-text", "LLM", "Czech TTS"],
        price_usd=99, cz_sam=30_000, demand=4, competition=2, complexity=4, regulatory=2, moat=4, cogs_pct=0.2,
        cz_segments=["Car services", "Clinics & physiotherapists", "Trades & craftsmen"],
        cz_competitors=[("Call centres / Daktela", "https://www.daktela.com", "Human or enterprise contact-centre", True),
                        ("US AI receptionists", "", "No natural Czech voice", False)],
        cz_notes="Natural-sounding Czech voice is the moat; disclose that callers are talking to AI (EU AI Act).",
    ),
    dict(
        name="AI Meeting Notes (Otter/Fireflies archetype)", url="https://fireflies.ai", category=AI,
        niche="Record, transcribe and summarise meetings", revenue_model="Subscription per user",
        revenue_note="Otter and Fireflies reached large scale",
        problem="Meeting notes are incomplete and action items get lost.",
        tech_stack=["Meeting bots", "ASR", "LLM summarisation"],
        price_usd=18, cz_sam=30_000, demand=3, competition=4, complexity=3, regulatory=3, moat=3, cogs_pct=0.15,
        cz_segments=["Czech SMEs & agencies", "Municipal councils", "Consultants"],
        cz_competitors=[("Beey", "https://www.beey.io", "Czech transcription", True),
                        ("Microsoft Copilot / Zoom AI", "", "Bundled with existing tools", False)],
        cz_notes="GDPR consent for recording is mandatory; EU data residency is a selling point.",
    ),
    dict(
        name="AI Legal Research Assistant for Czech Law (Harvey archetype)", url="https://www.harvey.ai",
        category=AI, niche="Q&A and drafting over Czech legislation and case law", revenue_model="Subscription per lawyer",
        revenue_note="Harvey and Casetext (acquired) proved lawyers pay for AI research",
        problem="Small law firms spend hours searching legislation and case law.",
        tech_stack=["RAG over legal corpus", "LLM", "Citation checking"],
        price_usd=90, cz_sam=8_000, demand=4, competition=3, complexity=4, regulatory=3, moat=5, cogs_pct=0.15,
        cz_segments=["Small law firms (advokátní kanceláře)", "In-house legal teams", "Tax advisers"],
        cz_competitors=[("Codexis", "https://www.codexis.cz", "Czech legal information system", True),
                        ("Beck-online / ASPI", "", "Established legal databases adding AI", True)],
        cz_notes="Czech legal corpus and case law are public; accuracy and citations are the whole product.",
    ),
    dict(
        name="AI Product Descriptions for E-shops (Hypotenuse archetype)", url="https://www.hypotenuse.ai",
        category=AI, niche="Bulk-generate product texts and translations", revenue_model="Subscription by product count",
        revenue_note="Hypotenuse AI and similar tools found strong e-commerce demand",
        problem="E-shops have thousands of products with missing or copied manufacturer descriptions.",
        tech_stack=["LLM APIs", "Shop API", "Feed import"],
        price_usd=39, cz_sam=30_000, demand=4, competition=3, complexity=2, regulatory=1, moat=3, cogs_pct=0.1,
        cz_segments=["Shoptet & Upgates merchants", "Dropshippers", "Wholesalers"],
        cz_competitors=[("ChatGPT (manual)", "", "Copy-paste status quo", False),
                        ("Shoptet AI add-ons", "https://doplnky.shoptet.cz", "Check existing add-ons", True)],
        cz_notes="Ship it as a Shoptet add-on with CZ/SK/PL/HU output for cross-border shops.",
    ),
    dict(
        name="AI Grant & Subsidy Finder (Instrumentl archetype)", url="https://www.instrumentl.com", category=AI,
        niche="Match firms to EU/national grants and draft applications", revenue_model="Subscription + success fee",
        revenue_note="Instrumentl built a large grant-discovery SaaS in the US",
        problem="SMEs don't know which dotace fit them and consultants charge high success fees.",
        tech_stack=["Scrapers", "LLM matching", "Document drafting"],
        price_usd=80, cz_sam=20_000, demand=4, competition=3, complexity=3, regulatory=2, moat=5,
        cz_segments=["Manufacturing SMEs", "Municipalities", "NGOs & schools"],
        cz_competitors=[("Grant consultancies (dotační poradci)", "", "Many; success fees 5-10%", True),
                        ("Official portals (e.g. MPO, OP TAK)", "", "Raw information only", True)],
        cz_notes="Czechia draws large EU funds (OP TAK, NPO); calls are complex and in Czech - strong local moat.",
    ),
    dict(
        name="Interior AI", url="https://interiorai.com", category=AI,
        niche="AI virtual staging & interior redesign", revenue_model="Monthly subscription",
        mrr_usd=40_000, revenue_note="Founder's open revenue posts; approximate",
        problem="Empty or dated property photos sell and rent slower.",
        tech_stack=["PHP", "Diffusion models", "Replicate"],
        price_usd=29, cz_sam=8_000, demand=3, competition=2, complexity=3, regulatory=1, moat=3, cogs_pct=0.2,
        cz_segments=["Realitní makléři listing on Sreality", "Developers", "Airbnb hosts"],
        cz_competitors=[("Human 3D visualisation studios", "", "Expensive, slow", True),
                        ("Global AI staging tools", "", "English-only", False)],
        cz_notes="Integrate with Sreality/Bezrealitky listing workflows used by Czech agents.",
    ),
    dict(
        name="AI CV & Cover Letter Builder (Kickresume archetype)", url="https://www.kickresume.com", category=AI,
        niche="AI-written CVs and cover letters", revenue_model="Monthly subscription",
        revenue_note="Kickresume (Bratislava) is a well-known CEE success in this niche",
        problem="Job seekers struggle to write a good CV, especially in a foreign language.",
        tech_stack=["React", "LLM APIs", "PDF templates"],
        audience="B2C", price_usd=10, cz_sam=100_000, demand=3, competition=4, complexity=2, regulatory=1, moat=2,
        cz_segments=["Job seekers on Jobs.cz", "Graduates", "Expats applying in Czech"],
        cz_competitors=[("Kickresume", "https://www.kickresume.com", "Slovak, strong in CZ", False),
                        ("Jobs.cz CV builder", "https://www.jobs.cz", "Free", True)],
    ),
    dict(
        name="AI Tutor for Přijímačky & Maturita (Khanmigo archetype)", url="https://www.khanmigo.ai", category=AI,
        niche="Adaptive practice for Czech entrance exams", revenue_model="Monthly subscription (parents pay)",
        revenue_note="Photomath and Khanmigo prove parents pay for AI tutoring",
        problem="Pupils preparing for CERMAT exams need practice and explanations; tutors are expensive.",
        tech_stack=["Next.js", "LLM tutor", "Exercise bank"],
        audience="B2C", price_usd=12, price_czk_override=249, cz_sam=120_000, demand=4, competition=3, complexity=3,
        regulatory=1, moat=5, cogs_pct=0.1,
        cz_segments=["Parents of 9th-graders (přijímačky)", "Maturita students", "Tutoring centres"],
        cz_competitors=[("Umíme to", "https://www.umimeto.org", "Czech adaptive practice platform", True),
                        ("Scio", "https://www.scio.cz", "Prep courses & mock tests", True),
                        ("Private tutors", "", "400-800 CZK/hour", True)],
        cz_notes="Strong seasonality (Jan-April). Aligning with the CERMAT exam format is the moat.",
    ),

    # ------------------------------------------------------------------ Finance & Admin
    dict(
        name="Cash-flow Forecasting for SMEs (Float archetype)", url="https://floatapp.com", category=FIN,
        niche="13-week cash forecasts from bank & invoice data", revenue_model="Subscription SaaS",
        revenue_note="Float (UK) grew serving small businesses and accountants",
        problem="SME owners find out about cash shortfalls too late.",
        tech_stack=["Python", "PSD2 bank APIs", "Invoicing APIs"],
        price_usd=49, cz_sam=30_000, demand=3, competition=2, complexity=3, regulatory=2, moat=3,
        cz_segments=["s.r.o. with 5-50 employees", "Accountants advising clients", "E-shops with stock"],
        cz_competitors=[("Excel", "", "Status quo", True),
                        ("Fakturoid / iDoklad reports", "", "Invoice-level only", True)],
        cz_notes="Pull data from Fakturoid/iDoklad APIs and Czech banks via PSD2.",
    ),
    dict(
        name="Automated Payment Reminders & Collections (Chaser archetype)", url="https://www.chaserhq.com",
        category=FIN, niche="Polite automated dunning, escalation and collections",
        revenue_model="Subscription SaaS", revenue_note="Chaser (UK) grew bootstrapped-first",
        problem="Late payments are common and chasing clients is awkward.",
        tech_stack=["Node.js", "Invoicing APIs", "Email/SMS"],
        price_usd=39, cz_sam=60_000, demand=4, competition=3, complexity=2, regulatory=2, moat=3,
        cz_segments=["B2B service firms", "Wholesalers", "Accounting firms for their clients"],
        cz_competitors=[("Fakturoid reminders", "https://www.fakturoid.cz", "Basic reminders", True),
                        ("Collection agencies", "", "Expensive, relationship-damaging", True)],
        cz_notes="Add statutory late-payment interest and the fixed recovery-cost claim automatically (verify amounts).",
    ),
    dict(
        name="Payroll for Micro-businesses (Gusto archetype)", url="https://gusto.com", category=FIN,
        niche="Simple payroll, payslips and social/health insurance filings", revenue_model="Subscription per employee",
        revenue_note="Gusto proved the model in the US; local rules make each country its own market",
        problem="Czech payroll (ČSSZ, health insurers, DPP/DPČ) is complex for firms with 1-10 staff.",
        tech_stack=["Python", "Rules engine", "Government e-filing"],
        price_usd=8, price_czk_override=990, cz_sam=60_000, demand=4, competition=4, complexity=5, regulatory=5, moat=4,
        cz_segments=["Micro s.r.o. with 1-10 staff", "Restaurants", "Accountants outsourcing payroll"],
        cz_competitors=[("Pohoda / Money payroll modules", "", "Accountant-oriented", True),
                        ("Payroll bureaus", "", "Human service", True)],
        cz_notes="Price per company. Very high regulatory burden - partner with a payroll accountant from day one.",
    ),
    dict(
        name="English Tax Returns for Expats in Czechia (TaxScouts archetype)", url="https://taxscouts.com",
        category=FIN, niche="Guided Czech tax return filing in English", revenue_model="One-off fee per return",
        revenue_note="TaxScouts (UK) and TurboTax prove per-return pricing",
        problem="Foreign employees and OSVČ struggle with Czech-only tax forms and deadlines.",
        tech_stack=["Next.js", "Form wizard", "Partner tax advisers"],
        audience="B2C", price_usd=80, price_czk_override=169, cz_sam=15_000, demand=4, competition=2, complexity=3,
        regulatory=3, moat=5,
        cz_segments=["Expat employees with side income", "Foreign OSVČ in Prague", "Returning Czechs with foreign income"],
        cz_competitors=[("Portál MOJE daně", "https://adisspr.mfcr.cz", "Official, free, Czech-only", True),
                        ("Tax advisers (daňoví poradci)", "", "3-8k CZK per return", True)],
        cz_notes="Priced ~1,990 CZK per annual return, shown as the ~169 CZK monthly equivalent. Highly seasonal (spring); pair with a licensed daňový poradce.",
    ),
    dict(
        name="Landlord Toolkit (Landlord Studio archetype)", url="https://www.landlordstudio.com", category=FIN,
        niche="Rent tracking, utility settlements and tenant communication", revenue_model="Subscription per unit",
        revenue_note="Landlord Studio and TurboTenant serve small landlords profitably",
        problem="Small landlords track rent, deposits and annual service-charge settlements in Excel.",
        tech_stack=["Next.js", "Bank API", "PDF generation"],
        price_usd=6, price_czk_override=149, cz_sam=150_000, demand=3, competition=2, complexity=2, regulatory=2, moat=4,
        cz_segments=["Owners of 1-10 flats", "Small property managers", "Expat landlords"],
        cz_competitors=[("Excel", "", "Status quo", True),
                        ("Bezrealitky / Sreality", "", "Listings, not management", True)],
        cz_notes="Annual settlement of services (vyúčtování služeb) has Czech legal rules - automate it.",
    ),
    dict(
        name="SVJ Building Management Portal (Buildium archetype)", url="https://www.buildium.com", category=FIN,
        niche="Portal for Czech owners' associations: votes, repair fund, documents", revenue_model="Subscription per building",
        revenue_note="Buildium and AppFolio scaled on association/property management",
        problem="SVJ committees run votes, repair funds and announcements via paper and email.",
        tech_stack=["Laravel", "Vue", "E-voting"],
        price_usd=40, price_czk_override=790, cz_sam=40_000, demand=4, competition=3, complexity=3, regulatory=3, moat=5,
        cz_segments=["SVJ committees (výbor SVJ)", "Property administrators (správcovské firmy)", "Housing co-ops (BD)"],
        cz_competitors=[("Property-administration firms' own tools", "", "Varied quality", True),
                        ("Email + noticeboard", "", "Status quo", True)],
        cz_notes="Czech SVJ rules (per rollam voting, repair fund) are law-specific - global tools don't fit.",
    ),
    dict(
        name="Supplier Risk & VAT-Reliability Monitoring (Creditsafe archetype)", url="https://www.creditsafe.com",
        category=FIN, niche="Monitor partners for insolvency, unreliable-VAT status and changes",
        revenue_model="Subscription by monitored companies", revenue_note="Creditsafe built a large business on this",
        problem="Paying an unreliable VAT payer or an insolvent supplier creates liability and losses.",
        tech_stack=["Python", "ARES / ISIR / VAT registry APIs", "Alerts"],
        price_usd=29, cz_sam=50_000, demand=3, competition=4, complexity=2, regulatory=1, moat=4,
        cz_segments=["Accounting firms", "Wholesalers", "Construction firms"],
        cz_competitors=[("Merk", "https://www.merk.cz", "Czech company data & monitoring", True),
                        ("Cribis", "https://www.cribis.cz", "Credit reports", True),
                        ("Hlídač státu", "https://www.hlidacstatu.cz", "Free transparency data", True)],
        cz_notes="Paying to a non-published account of an unreliable VAT payer triggers joint VAT liability.",
    ),
    dict(
        name="Online s.r.o. Formation & Virtual Office (Stripe Atlas archetype)", url="https://stripe.com/atlas",
        category=FIN, niche="Guided company formation, registered address and mail scanning",
        revenue_model="One-off fee + monthly address subscription", revenue_note="Stripe Atlas and Firstbase proved demand",
        problem="Founders, especially foreigners, find setting up an s.r.o. confusing.",
        tech_stack=["Next.js", "Notary partner workflow", "Mail scanning"],
        price_usd=40, price_czk_override=690, cz_sam=30_000, demand=3, competition=5, complexity=3, regulatory=4, moat=3,
        cz_segments=["Foreign founders in Prague", "Freelancers switching to s.r.o.", "Holding structures"],
        cz_competitors=[("Online formation services", "", "Many established providers", True),
                        ("Virtual-office providers", "", "Commodity pricing", True)],
        cz_notes="Crowded; an English-first, founder-friendly angle is the only real differentiator.",
    ),

    # ------------------------------------------------------------------ Local Services
    dict(
        name="Home Cleaning Marketplace (Helpling archetype)", url="https://www.helpling.com", category=LOC,
        niche="Book vetted cleaners online with fixed prices", revenue_model="Commission per booking",
        revenue_note="Handy and Helpling proved demand in large cities",
        problem="Finding reliable cleaners is word-of-mouth only and scheduling is manual.",
        tech_stack=["Next.js", "Stripe Connect", "Scheduling"],
        audience="B2C", price_usd=30, price_czk_override=600, cz_sam=40_000, demand=4, competition=3, complexity=3,
        regulatory=3, moat=3,
        cz_segments=["Prague professionals", "Expat households", "Airbnb hosts"],
        cz_competitors=[("Local cleaning agencies", "", "Phone booking", True),
                        ("Bazoš / Facebook ads", "https://www.bazos.cz", "Informal", True)],
        cz_notes="Price = commission per active household per month. Cleaners' status (OSVČ vs. employees) is a key legal question.",
    ),
    dict(
        name="Tradesperson Quote Marketplace (Checkatrade archetype)", url="https://www.checkatrade.com",
        category=LOC, niche="Get quotes from vetted plumbers, electricians and builders",
        revenue_model="Lead fees / tradesperson subscription", revenue_note="Checkatrade and MyBuilder built large UK businesses",
        problem="Homeowners can't find reliable tradespeople; good tradespeople hate cold leads.",
        tech_stack=["Next.js", "Lead routing", "Reviews"],
        price_usd=40, price_czk_override=790, cz_sam=30_000, demand=4, competition=4, complexity=3, regulatory=1, moat=2,
        cz_segments=["Craftsmen (řemeslníci)", "Homeowners renovating flats", "Property managers"],
        cz_competitors=[("Nejřemeslníci.cz", "https://www.nejremeslnici.cz", "Czech craftsman marketplace", True),
                        ("Firmy.cz", "https://www.firmy.cz", "Directory", True)],
    ),
    dict(
        name="Driving School Management & Theory App", url="https://www.drivingschoolsoftware.com", category=LOC,
        niche="Lesson booking, instructor calendars and theory-test practice", revenue_model="Subscription per school",
        revenue_note="Many profitable niche vertical-SaaS vendors serve driving schools worldwide",
        problem="Driving schools manage lessons by phone and paper; students practise theory in outdated apps.",
        tech_stack=["React Native", "Node.js", "Official question bank"],
        price_usd=60, price_czk_override=1_290, cz_sam=1_200, demand=3, competition=3, complexity=2, regulatory=2, moat=5,
        cz_segments=["Driving schools (autoškoly)", "Students preparing for the theory exam"],
        cz_competitors=[("Free theory-test apps", "", "Question practice only", True),
                        ("Paper diaries / phone", "", "Status quo", True)],
        cz_notes="Small market (~1,000+ schools) - plan Slovakia early.",
    ),
    dict(
        name="Kids' Clubs & Camps Booking (ActivityHero archetype)", url="https://www.activityhero.com", category=LOC,
        niche="Registrations, payments and attendance for kroužky and summer camps",
        revenue_model="Subscription + booking fee", revenue_note="ActivityHero, Sawyer and ClassForKids proved the model",
        problem="Clubs collect registrations via Google Forms and chase payments by bank transfer.",
        tech_stack=["Next.js", "QR platba", "Parent app"],
        price_usd=40, price_czk_override=690, cz_sam=15_000, demand=4, competition=2, complexity=2, regulatory=2, moat=4,
        cz_segments=["After-school clubs (kroužky)", "Summer camp organisers (příměstské tábory)", "Sports clubs"],
        cz_competitors=[("Google Forms + bank transfer", "", "Status quo", True),
                        ("Club websites / Facebook", "", "No payments or attendance", True)],
        cz_notes="Summer day camps are hugely popular in CZ; QR platba + automatic payment pairing is a killer feature.",
    ),
    dict(
        name="Fitness & Yoga Studio Software (Mindbody archetype)", url="https://www.mindbodyonline.com", category=LOC,
        niche="Class schedules, memberships and passes", revenue_model="Subscription per studio",
        revenue_note="Mindbody, Glofox and Momence proved the vertical",
        problem="Studios juggle class bookings, passes and payments in several tools.",
        tech_stack=["React Native", "Stripe/Comgate", "Scheduling"],
        price_usd=60, cz_sam=4_000, demand=3, competition=4, complexity=3, regulatory=1, moat=2,
        cz_segments=["Yoga & pilates studios", "CrossFit boxes", "Dance schools"],
        cz_competitors=[("Reservio / Reservanto", "", "Czech booking systems", True),
                        ("Mindbody / Momence", "", "", False)],
        cz_notes="Integrate MultiSport-card check-ins, widely used as an employee benefit in CZ.",
    ),
    dict(
        name="Tutoring Marketplace (Preply archetype)", url="https://preply.com", category=LOC,
        niche="Match pupils with tutors, schedule and pay online", revenue_model="Commission per lesson",
        revenue_note="Preply and Wyzant scaled globally",
        problem="Parents struggle to find reliable tutors; tutors want steady students.",
        tech_stack=["Next.js", "Video calls", "Stripe Connect"],
        audience="B2C", price_usd=30, price_czk_override=400, cz_sam=60_000, demand=3, competition=3, complexity=3,
        regulatory=1, moat=3,
        cz_segments=["Parents of pupils before přijímačky", "University students", "Adults learning languages"],
        cz_competitors=[("Preply / italki", "", "Global, language-focused", False),
                        ("Bazoš / Facebook groups", "https://www.bazos.cz", "Informal", True)],
        cz_notes="Price = commission per active family per month.",
    ),
    dict(
        name="Home-care & Senior Companion Matching (Honor archetype)", url="https://www.joinhonor.com", category=LOC,
        niche="Vetted carers for seniors at home", revenue_model="Commission on care hours",
        revenue_note="Honor and Home Instead prove large demand in ageing societies",
        problem="Families can't find trustworthy carers for elderly parents quickly.",
        tech_stack=["Next.js", "Scheduling", "Background checks"],
        audience="B2C", price_usd=150, price_czk_override=2_500, cz_sam=20_000, demand=4, competition=3, complexity=4,
        regulatory=4, moat=3,
        cz_segments=["Adult children of seniors", "Seniors receiving care allowance (příspěvek na péči)"],
        cz_competitors=[("Home-care agencies & charities", "", "Established, capacity-limited", True),
                        ("Informal carers via ads", "", "No vetting", True)],
        cz_notes="Social-services registration may be required depending on the service - get legal advice.",
    ),
    dict(
        name="Mobile Car Detailing Booking", url="https://www.getspiffy.com", category=LOC,
        niche="On-site car washing & detailing booked online", revenue_model="Per-service + memberships",
        revenue_note="Spiffy and many local operators prove the model",
        problem="Busy car owners have no time to visit a car wash.",
        tech_stack=["Booking site", "Route planning"],
        audience="B2C", price_usd=60, price_czk_override=1_500, cz_sam=20_000, demand=3, competition=3, complexity=3,
        regulatory=3, moat=2, cogs_pct=0.45,
        cz_segments=["Prague office parks (car fleets)", "Premium car owners", "Car-sharing fleets"],
        cz_competitors=[("Car washes & detailing studios", "", "Many local", True),
                        ("Waterless wash operators", "", "Few in Prague", True)],
        cz_notes="Water-disposal rules limit washing on public streets - waterless products avoid this.",
    ),
    dict(
        name="Laundry Pickup & Delivery (Rinse archetype)", url="https://www.rinse.com", category=LOC,
        niche="Scheduled laundry & dry-cleaning pickup", revenue_model="Per-order + subscription",
        revenue_note="Rinse and Laundryheap scaled in big cities",
        problem="Busy professionals lose weekend time on laundry and dry cleaning.",
        tech_stack=["Next.js", "Route planning", "Partner laundries"],
        audience="B2C", price_usd=60, price_czk_override=1_200, cz_sam=15_000, demand=3, competition=2, complexity=4,
        regulatory=2, moat=2, cogs_pct=0.55,
        cz_segments=["Prague professionals", "Expats", "Airbnb hosts"],
        cz_competitors=[("Local dry cleaners", "", "Walk-in", True),
                        ("Laundry services for hotels", "", "B2B only", True)],
    ),

    # ------------------------------------------------------------------ Hospitality & Gastro
    dict(
        name="Restaurant Inventory & Food-cost Control (MarketMan archetype)", url="https://www.marketman.com",
        category=HOS, niche="Stock, recipes costing and supplier orders", revenue_model="Subscription per venue",
        revenue_note="MarketMan and meez serve thousands of restaurants",
        problem="Restaurants don't know their real food cost per dish; waste is invisible.",
        tech_stack=["React", "POS integrations", "OCR for supplier invoices"],
        price_usd=80, price_czk_override=1_490, cz_sam=15_000, demand=4, competition=3, complexity=3, regulatory=1, moat=3,
        cz_segments=["Independent restaurants", "Small restaurant groups", "Hotel kitchens"],
        cz_competitors=[("Dotykačka / Storyous stock modules", "", "POS-integrated basics", True),
                        ("Excel", "", "Status quo", True)],
    ),
    dict(
        name="Online Table Reservations (OpenTable archetype)", url="https://www.opentable.com", category=HOS,
        niche="Online booking, deposits and no-show protection for restaurants", revenue_model="Subscription + per-cover",
        revenue_note="OpenTable and Resy proved the model",
        problem="Restaurants lose revenue to no-shows and phone bookings.",
        tech_stack=["Next.js", "Payment gateway", "Widgets"],
        price_usd=50, cz_sam=15_000, demand=3, competition=4, complexity=3, regulatory=1, moat=2,
        cz_segments=["Prague restaurants", "Wine bars", "Brunch places"],
        cz_competitors=[("Restu", "https://www.restu.cz", "Czech restaurant guide & reservations", True),
                        ("Bookio", "https://www.bookio.com", "Slovak booking system", False),
                        ("Google Reserve integrations", "", "", False)],
    ),
    dict(
        name="Guesthouse Booking Engine & Channel Manager (Little Hotelier archetype)",
        url="https://www.littlehotelier.com", category=HOS,
        niche="Direct bookings, channel sync and guest registration", revenue_model="Subscription per property",
        revenue_note="Little Hotelier and Cloudbeds serve small properties profitably",
        problem="Small guesthouses pay high OTA commissions and double-book across channels.",
        tech_stack=["Node.js", "OTA APIs", "Payment gateway"],
        price_usd=60, cz_sam=10_000, demand=3, competition=4, complexity=4, regulatory=3, moat=3,
        cz_segments=["Pensions (penziony)", "Small hotels", "Chalets & cottages (chaty)"],
        cz_competitors=[("Previo", "https://www.previo.cz", "Czech hotel system leader", True),
                        ("Cloudbeds / Smoobu", "", "", False)],
        cz_notes="Guest registration (foreigner police reporting) and local accommodation fees need automating.",
    ),
    dict(
        name="Office Catering Marketplace (ezCater archetype)", url="https://www.ezcater.com", category=HOS,
        niche="Order catering for meetings and events from local caterers", revenue_model="Commission per order",
        revenue_note="ezCater scaled to a very large marketplace in the US",
        problem="Office managers order catering by phone with no invoicing consistency.",
        tech_stack=["Next.js", "Stripe Connect", "Invoicing API"],
        price_usd=100, price_czk_override=1_800, cz_sam=5_000, demand=3, competition=3, complexity=3, regulatory=2, moat=3,
        cz_segments=["Prague office managers", "Coworkings", "Event agencies"],
        cz_competitors=[("Wolt for Work / Foodora", "", "Delivery, not catering", False),
                        ("Caterers directly", "", "Phone/email", True)],
        cz_notes="Price = commission per active company per month.",
    ),
    dict(
        name="Airbnb Cleaning Turnover Marketplace (Turno archetype)", url="https://turno.com", category=HOS,
        niche="Auto-schedule cleaners from booking calendars", revenue_model="Subscription per property + fees",
        revenue_note="Turno (formerly TurnoverBnB) built a large host-cleaner marketplace",
        problem="Hosts coordinate cleaners manually after every checkout.",
        tech_stack=["Node.js", "iCal sync", "Mobile app"],
        price_usd=10, price_czk_override=390, cz_sam=8_000, demand=4, competition=2, complexity=3, regulatory=2, moat=3,
        cz_segments=["Prague Airbnb hosts", "Co-hosting companies", "Cleaning freelancers"],
        cz_competitors=[("WhatsApp groups", "", "Status quo", True),
                        ("Property-management companies", "", "Full-service", True)],
    ),
    dict(
        name="Digital Loyalty Cards for Cafés (Stamp Me archetype)", url="https://www.stampme.com", category=HOS,
        niche="Stamp cards in phone wallets with push offers", revenue_model="Subscription per venue",
        revenue_note="Stamp Me and Loopy Loyalty are profitable niche SaaS",
        problem="Paper stamp cards get lost and give the café no customer data.",
        tech_stack=["Apple/Google Wallet passes", "Next.js"],
        price_usd=30, price_czk_override=490, cz_sam=12_000, demand=3, competition=2, complexity=2, regulatory=2, moat=3,
        cz_segments=["Speciality cafés", "Bakeries", "Barbershops"],
        cz_competitors=[("Paper stamp cards", "", "Status quo", True),
                        ("POS loyalty modules", "", "Basic, POS-locked (verify)", True)],
    ),
    dict(
        name="Surplus Food Marketplace (Too Good To Go archetype)", url="https://www.toogoodtogo.com", category=HOS,
        niche="Sell end-of-day surplus food at a discount", revenue_model="Commission + annual fee",
        revenue_note="Too Good To Go is VC-backed and active in CZ",
        problem="Bakeries and restaurants throw away edible food every day.",
        tech_stack=["Mobile app", "Payments"],
        price_usd=30, price_czk_override=400, cz_sam=15_000, demand=3, competition=5, complexity=3, regulatory=2, moat=1,
        cz_segments=["Bakeries", "Supermarkets", "Canteens"],
        cz_competitors=[("Too Good To Go", "https://www.toogoodtogo.com", "Market leader, active in CZ", False),
                        ("Food banks (potravinové banky)", "", "Donation alternative", True)],
    ),
    dict(
        name="Craft Beer Subscription Box", url="https://www.beer52.com", category=HOS,
        niche="Monthly curated craft beers from small breweries", revenue_model="Monthly subscription",
        revenue_note="Beer52 (UK) scaled a large beer-subscription business",
        problem="Craft-beer fans want discovery; small breweries want new customers.",
        tech_stack=["Shoptet/WooCommerce", "Recurring payments", "Logistics partner"],
        audience="B2C", price_usd=40, price_czk_override=790, cz_sam=15_000, demand=3, competition=3, complexity=3,
        regulatory=3, moat=4, cogs_pct=0.6,
        cz_segments=["Craft-beer fans", "Corporate gifts", "Expats"],
        cz_competitors=[("Brewery e-shops", "", "Single-brewery", True),
                        ("Beer subscription e-shops", "", "Several small ones - verify", True)],
        cz_notes="Alcohol shipping requires age verification on delivery; excise is paid by breweries.",
    ),

    # ------------------------------------------------------------------ Communities & Marketplaces
    dict(
        name="Coworking Day-pass Marketplace (Deskpass archetype)", url="https://www.deskpass.com", category=COM,
        niche="One membership for many coworkings", revenue_model="Membership fee, revenue share with spaces",
        revenue_note="Deskpass and Croissant proved the model in US cities",
        problem="Remote workers want flexible desks in different neighbourhoods.",
        tech_stack=["Mobile app", "Check-in QR"],
        audience="B2C", price_usd=150, price_czk_override=2_900, cz_sam=5_000, demand=2, competition=3, complexity=3,
        regulatory=1, moat=2, cogs_pct=0.6,
        cz_segments=["Prague remote workers", "Digital nomads", "Companies with hybrid teams"],
        cz_competitors=[("Coworking memberships directly", "", "Status quo", True),
                        ("Global workspace networks", "", "", False)],
    ),
    dict(
        name="Vinted", url="https://www.vinted.com", category=COM,
        niche="Second-hand fashion marketplace", revenue_model="Buyer protection fee",
        revenue_note="Lithuanian unicorn; very popular in Czechia",
        problem="People want to sell used clothes easily and buy cheaply.",
        tech_stack=["Rails", "Mobile apps", "Logistics integrations"],
        audience="B2C", price_usd=5, price_czk_override=60, cz_sam=500_000, demand=4, competition=5, complexity=5,
        regulatory=2, moat=1,
        cz_segments=["Czech women 18-45", "Parents (kids' clothing)"],
        cz_competitors=[("Vinted", "https://www.vinted.cz", "Dominant in CZ", False),
                        ("Bazoš", "https://www.bazos.cz", "Classifieds", True)],
        cz_notes="Included as a benchmark: the category is proven but already won - only niche verticals remain.",
    ),
    dict(
        name="Peer-to-peer Equipment Rental (Fat Llama archetype)", url="https://fatllama.com", category=COM,
        niche="Rent cameras, tools and gear from neighbours", revenue_model="Commission per rental",
        revenue_note="Fat Llama raised VC; category still unproven at scale",
        problem="Expensive gear sits unused; renters want flexible access.",
        tech_stack=["Next.js", "Stripe Connect", "Insurance partner"],
        audience="B2C", price_usd=15, price_czk_override=250, cz_sam=20_000, demand=2, competition=2, complexity=4,
        regulatory=3, moat=2,
        cz_segments=["Filmmakers & photographers", "DIY renovators", "Campers"],
        cz_competitors=[("Rental shops (půjčovny)", "", "Established offline", True),
                        ("Bazoš", "https://www.bazos.cz", "Informal", True)],
        cz_notes="Insurance and damage disputes are the hard part.",
    ),
    dict(
        name="Private Parking Space Sharing (JustPark archetype)", url="https://www.justpark.com", category=COM,
        niche="Rent out private driveways and garage spots", revenue_model="Commission per booking",
        revenue_note="JustPark scaled in the UK",
        problem="Parking in city centres is scarce while private spots sit empty during the day.",
        tech_stack=["Mobile app", "Maps", "Smart gate integrations"],
        audience="B2C", price_usd=20, price_czk_override=350, cz_sam=40_000, demand=4, competition=2, complexity=3,
        regulatory=3, moat=3,
        cz_segments=["Prague residents with garage spots", "Commuters", "Office buildings"],
        cz_competitors=[("Municipal parking apps", "", "Public zones only", True),
                        ("Bazoš garage ads", "", "Long-term rentals only", True)],
        cz_notes="Prague's paid parking zones push demand; building-rule (SVJ) permissions may be needed.",
    ),
    dict(
        name="Local Freelance Marketplace (Upwork archetype)", url="https://www.upwork.com", category=COM,
        niche="Hire Czech freelancers for short projects", revenue_model="Commission / membership",
        revenue_note="Upwork and Fiverr are public; local communities work better in small markets",
        problem="Companies struggle to find vetted local freelancers who invoice correctly.",
        tech_stack=["Next.js", "Profiles & reviews", "Escrow"],
        price_usd=40, price_czk_override=690, cz_sam=10_000, demand=3, competition=4, complexity=3, regulatory=2, moat=3,
        cz_segments=["Startups & agencies", "OSVČ freelancers", "SMEs"],
        cz_competitors=[("Na volné noze", "https://www.navolnenoze.cz", "Czech freelancer community", True),
                        ("Upwork / Fiverr", "", "", False)],
        cz_notes="Beware švarcsystém (disguised employment) rules for long-term freelance engagements.",
    ),
    dict(
        name="Czech for Foreigners: Exam-prep Marketplace", url="https://www.italki.com", category=COM,
        niche="Tutors and courses targeting Czech-language residency & citizenship exams",
        revenue_model="Commission per lesson + course sales", revenue_note="italki and Preply proved online language tutoring",
        problem="Expats need a specific Czech level for permanent residence or citizenship and struggle to prepare.",
        tech_stack=["Next.js", "Video calls", "Mock exams"],
        audience="B2C", price_usd=40, price_czk_override=700, cz_sam=30_000, demand=4, competition=3, complexity=2,
        regulatory=1, moat=5,
        cz_segments=["Expats applying for permanent residence", "Applicants for citizenship", "Relocating IT specialists"],
        cz_competitors=[("Language schools in Prague", "", "Group classes", True),
                        ("italki / Preply", "", "Not exam-focused", False)],
        cz_notes="Required level is A2 for permanent residence and B1 for citizenship (verify current rules).",
    ),
    dict(
        name="Mid-term Rentals for Students & Expats (HousingAnywhere archetype)",
        url="https://housinganywhere.com", category=COM,
        niche="Verified furnished rentals booked online for 1-12 months", revenue_model="Tenant & landlord fees",
        revenue_note="HousingAnywhere and Spotahome scaled across EU cities",
        problem="Newcomers can't view flats in person and fear scams; landlords fear bad tenants.",
        tech_stack=["Next.js", "Payments & escrow", "ID verification"],
        audience="B2C", price_usd=40, price_czk_override=800, cz_sam=30_000, demand=4, competition=4, complexity=4,
        regulatory=3, moat=2,
        cz_segments=["International students", "Relocating employees", "Landlords in Prague 2-7"],
        cz_competitors=[("Flatio", "https://www.flatio.com", "Czech mid-term rental platform", True),
                        ("Sreality / Bezrealitky", "", "Long-term rentals", True),
                        ("HousingAnywhere", "https://housinganywhere.com", "", False)],
        cz_notes="Price = fees per active tenant-month.",
    ),
]
