"""Proven business models from the USA, Canada and Latin America."""

from ._helpers import AI, COM, CRE, D2C, DEV, ECOM, EDU, FIN, HEA, HOS, LOC, MKT, m

VC = "VC-backed; proves the category"
BOOT = "Bootstrapped and profitable; revenue not public"

MODELS = [
    # ---------------------------------------------------------------- USA - software
    m("Basecamp", "USA", "https://basecamp.com", DEV, "Simple project management & team communication",
      "Flat-price subscription", 299, "Teams drown in email threads and scattered to-do lists.",
      note="Bootstrapped for 20+ years by 37signals", d=2, c=4, x=3, mo=1),
    m("Calendly", "USA", "https://calendly.com", DEV, "Scheduling links for meetings", "Freemium subscription", 12,
      "Booking meetings takes endless back-and-forth emails.", note="Grew largely bootstrapped before raising",
      d=3, c=4, x=2, mo=1, comps=[("Reservio", "https://www.reservio.cz", "Czech booking system", True)]),
    m("Zapier", "USA", "https://zapier.com", DEV, "No-code automation between web apps", "Freemium subscription", 30,
      "Small teams copy data between apps by hand.", note="Famously capital-efficient; multi-$100M ARR",
      d=3, c=4, x=5, mo=1),
    m("Baremetrics", "USA", "https://baremetrics.com", DEV, "Subscription analytics for Stripe businesses",
      "Subscription SaaS", 129, "SaaS founders can't see MRR, churn and LTV at a glance.", note=BOOT,
      sam=800, d=1, c=3, x=3, mo=1),
    m("Tuple", "USA", "https://tuple.app", DEV, "Remote pair-programming app", "Subscription per user", 30,
      "Screen-sharing tools are laggy for pair programming.", note=BOOT, sam=3_000, d=1, c=3, x=4, mo=1),
    m("SavvyCal", "USA", "https://savvycal.com", DEV, "Polished scheduling links", "Subscription SaaS", 12,
      "Recipients dislike impersonal booking pages.", note=BOOT, d=2, c=4, x=2, mo=1),
    m("Userlist", "USA", "https://userlist.com", MKT, "Behaviour-based email for SaaS", "Subscription SaaS", 100,
      "SaaS companies need onboarding emails triggered by product usage.", note=BOOT, sam=800, d=1, c=3, mo=1),
    m("Buttondown", "USA", "https://buttondown.com", CRE, "Minimalist newsletter platform", "Subscription SaaS", 9,
      "Writers want a simple, markdown-friendly newsletter tool.", note="Solo-founder bootstrapped",
      d=2, c=4, x=2, mo=1),
    m("Mailchimp", "USA", "https://mailchimp.com", MKT, "Email marketing for small businesses",
      "Freemium subscription", 20, "Small businesses need easy email campaigns.",
      note="Bootstrapped to a $12B acquisition by Intuit", d=3, c=5, x=4, mo=1,
      comps=[("Ecomail", "https://ecomail.cz", "Czech email marketing", True),
             ("SmartEmailing", "https://www.smartemailing.cz", "Czech automation", True)]),
    m("Help Scout", "USA", "https://www.helpscout.com", DEV, "Shared inbox & help desk for small teams",
      "Subscription per user", 25, "Support emails get lost in personal inboxes.", note="Capital-efficient, profitable",
      d=3, c=4, x=3, mo=2, comps=[("Supportbox", "https://supportbox.cz", "Czech help desk", True)]),
    m("Canny", "USA", "https://canny.io", DEV, "Customer feedback boards & roadmaps", "Subscription SaaS", 79,
      "Product teams lose feature requests across channels.", note=BOOT, sam=1_500, d=1, c=3, mo=1),
    m("Webflow", "USA", "https://webflow.com", DEV, "Visual website builder for designers", "Subscription SaaS", 29,
      "Designers depend on developers to ship websites.", note=VC, d=3, c=4, x=5, mo=1),
    m("Bubble", "USA", "https://bubble.io", DEV, "No-code web app builder", "Subscription SaaS", 32,
      "Non-technical founders can't build software.", note=VC, sam=3_000, d=2, c=3, x=5, mo=1),
    m("Loom", "USA", "https://www.loom.com", DEV, "Async screen-recording videos", "Freemium per user", 15,
      "Meetings are used for things a 2-minute video could explain.", note="Acquired by Atlassian",
      d=2, c=4, x=4, mo=1),
    m("Lemon Squeezy", "USA", "https://www.lemonsqueezy.com", FIN, "Merchant of record for digital products",
      "Transaction fee", 50, "Selling software globally means handling VAT in dozens of countries.",
      note="Acquired by Stripe", sam=2_000, d=2, c=3, x=5, r=4, mo=1),
    m("Jotform", "USA", "https://www.jotform.com", DEV, "Form builder with 10k+ templates", "Freemium subscription", 34,
      "Organisations need forms, payments and approvals without code.",
      note="Bootstrapped by its Turkish-American founder for 15+ years", d=2, c=4, x=3, mo=1,
      comps=[("Survio", "https://www.survio.com", "Brno-based survey tool", True)]),
    m("Close", "USA", "https://www.close.com", MKT, "Sales CRM with built-in calling", "Subscription per user", 49,
      "Inside-sales teams juggle CRM, dialer and email tools.", note=BOOT, d=2, c=4, x=3, mo=1,
      comps=[("Raynet", "https://raynet.cz", "Czech CRM", True)]),
    m("PandaDoc", "USA", "https://www.pandadoc.com", DEV, "Proposals, quotes and e-signatures", "Subscription per user",
      35, "Sales documents are built by hand and chased by email.", note=VC, d=3, c=4, x=3, r=2, mo=2,
      comps=[("Signi", "https://www.signi.com", "Czech e-signature", True)]),
    m("Follow Up Boss", "USA", "https://www.followupboss.com", MKT, "CRM built for real-estate agents",
      "Subscription per user", 69, "Agents lose leads from portals because follow-up is slow.",
      note="Bootstrapped, acquired by Zillow", sam=6_000, d=3, c=3, x=3, mo=3,
      segs=["Realitní makléři", "Small real-estate agencies"],
      cz="Integrate Sreality and Bezrealitky lead e-mails, the main Czech property portals."),
    m("BambooHR", "USA", "https://www.bamboohr.com", DEV, "HR software for small & mid-size businesses",
      "Subscription per employee", 8, "HR data lives in spreadsheets and email.", note="Bootstrapped for over a decade",
      czk=2_490, d=3, c=3, x=3, r=3, mo=3, cz="Price per company; Czech employment paperwork is a localisation hook."),
    m("Rewardful", "USA", "https://www.rewardful.com", MKT, "Affiliate & referral programs for SaaS",
      "Subscription SaaS", 49, "SaaS companies want affiliates without custom tracking code.", note=BOOT,
      sam=800, d=1, c=2, x=3, mo=1),
    m("Starter Story", "USA", "https://www.starterstory.com", CRE, "Database of founder case studies",
      "Membership subscription", 20, "Aspiring founders want proven business ideas with real numbers.",
      note="Founder-reported profitable media + membership business", aud="B2C", sam=20_000, d=2, c=2, x=2, mo=3,
      cz="A Czech-language equivalent could feature local founders (similar to this app's idea)."),
    m("Exploding Topics", "USA", "https://explodingtopics.com", MKT, "Early detection of trending topics & products",
      "Subscription SaaS", 39, "Marketers and founders spot trends too late.", note="Acquired by Semrush",
      sam=2_000, d=2, c=2, x=3, mo=2),
    m("Jasper", "USA", "https://www.jasper.ai", AI, "AI copywriting for marketing teams", "Subscription per seat", 49,
      "Marketing teams need on-brand copy at volume.", note=VC, d=3, c=4, x=3, mo=2),
    m("Gamma", "USA", "https://gamma.app", AI, "AI-generated presentations and docs", "Freemium subscription", 10,
      "Making slide decks takes hours.", note=VC, d=3, c=3, x=4, mo=1),
    m("Opus Clip", "USA", "https://www.opus.pro", AI, "AI cuts long videos into short social clips",
      "Freemium subscription", 15, "Creators can't repurpose long videos fast enough.", note=VC, d=3, c=3, x=4, mo=2,
      cogs=0.15),
    m("DoNotPay", "USA", "https://donotpay.com", AI, "AI consumer-rights assistant", "Consumer subscription", 12,
      "Consumers give up on refunds, parking appeals and cancellations.", note="VC-backed; regulatory controversy",
      aud="B2C", d=2, c=2, x=4, r=5, mo=3),
    m("Freed", "USA", "https://www.getfreed.ai", HEA, "AI medical scribe for small clinics", "Subscription per clinician",
      99, "Doctors spend hours on documentation after every shift.", note=VC, sam=15_000, d=4, c=2, x=4, r=4, mo=4,
      cogs=0.15, segs=["Private GPs (praktičtí lékaři)", "Specialist outpatient clinics", "Physiotherapists"],
      cz="Czech medical terminology and GDPR special-category data rules are the moat and the risk."),
    m("SimplePractice", "USA", "https://www.simplepractice.com", HEA, "Practice management for therapists",
      "Subscription per clinician", 49, "Solo therapists juggle booking, notes and billing.", note=VC,
      sam=6_000, d=3, c=2, x=3, r=3, mo=3, segs=["Psychotherapists", "Psychologists", "Nutritionists"]),
    m("BetterHelp", "USA", "https://www.betterhelp.com", HEA, "Online therapy marketplace", "Weekly subscription",
      260, "Finding an available therapist takes weeks.", note="Public (Teladoc); very large",
      aud="B2C", czk=3_200, sam=40_000, d=4, c=3, x=3, r=4, mo=3, cogs=0.6,
      comps=[("Hedepy", "https://www.hedepy.cz", "Czech online therapy platform", True)]),
    m("Headspace", "USA", "https://www.headspace.com", HEA, "Meditation & mental-health app", "Consumer subscription",
      13, "People want guided mental-health habits.", note=VC, aud="B2C", d=2, c=4, x=4, mo=2),
    m("Zocdoc", "USA", "https://www.zocdoc.com", HEA, "Doctor search & online booking", "Per-booking fee to doctors",
      60, "Patients can't see doctors' availability online.", note=VC, sam=10_000, d=4, c=3, x=4, r=3, mo=3),
    m("Outschool", "USA", "https://outschool.com", EDU, "Live small-group online classes for kids",
      "Commission on classes", 60, "Parents want engaging extracurriculars beyond school.", note=VC,
      aud="B2C", czk=500, d=3, c=2, x=3, mo=3),
    m("Duolingo", "USA", "https://www.duolingo.com", EDU, "Gamified language learning", "Freemium subscription",
      13, "Language learning is boring and hard to stick with.", note="Public; category benchmark",
      aud="B2C", d=3, c=5, x=5, mo=1),

    # ---------------------------------------------------------------- USA - services & marketplaces
    m("Housecall Pro", "USA", "https://www.housecallpro.com", LOC, "Field-service software for home-service pros",
      "Subscription SaaS", 65, "Plumbers and cleaners run quotes, jobs and invoices on paper.", note=VC,
      d=4, c=2, x=4, mo=3, segs=["Plumbers & electricians", "Cleaning companies", "HVAC installers"]),
    m("Thumbtack", "USA", "https://www.thumbtack.com", LOC, "Marketplace for local professionals", "Pay-per-lead",
      30, "People can't compare local pros quickly.", note=VC, czk=600, d=3, c=4, x=4, mo=2,
      comps=[("Nejřemeslníci.cz", "https://www.nejremeslnici.cz", "Czech craftsman marketplace", True)]),
    m("TaskRabbit", "USA", "https://www.taskrabbit.com", LOC, "On-demand help for odd jobs", "Service fee",
      25, "Assembling furniture or moving boxes needs extra hands.", note="Acquired by IKEA", aud="B2C",
      czk=400, d=3, c=2, x=3, r=3, mo=2),
    m("Care.com", "USA", "https://www.care.com", LOC, "Marketplace for childcare & senior carers",
      "Membership subscription", 40, "Families struggle to find trusted carers.", note="Acquired by IAC",
      aud="B2C", czk=490, d=3, c=3, x=3, r=3, mo=2),
    m("LawnStarter", "USA", "https://www.lawnstarter.com", LOC, "On-demand lawn care booking", "Commission per job",
      40, "Homeowners can't find reliable gardeners.", note=VC, aud="B2C", czk=500, d=2, c=2, x=3, mo=2,
      cz="Seasonal (April-October); strong in suburbs around Prague and Brno."),
    m("Nextdoor", "USA", "https://nextdoor.com", COM, "Neighbourhood social network", "Local advertising",
      50, "Neighbours have no trusted place to share local news and recommendations.", note="Public",
      d=2, c=3, x=4, mo=2, comps=[("Neighbourhood Facebook groups", "", "Free default", False)]),
    m("Etsy", "USA", "https://www.etsy.com", COM, "Marketplace for handmade & vintage goods",
      "Listing fee + commission", 20, "Makers need a place to sell handmade products.", note="Public; category benchmark",
      czk=300, d=3, c=5, x=5, mo=1, comps=[("Fler.cz", "https://www.fler.cz", "Czech handmade marketplace", True)]),
    m("Cameo", "USA", "https://www.cameo.com", COM, "Personalised video messages from celebrities",
      "Commission per video", 50, "Fans want personal shout-outs for gifts.", note=VC, aud="B2C", czk=900,
      sam=20_000, d=2, c=2, x=3, mo=4, cz="Czech TV, sports and YouTube personalities are a distinct local roster."),
    m("Toptal", "USA", "https://www.toptal.com", COM, "Vetted elite freelance developers", "Markup on hourly rates",
      2000, "Companies can't vet freelance developers quickly.", note="Bootstrapped to large scale",
      czk=20_000, sam=2_000, d=2, c=3, x=3, mo=2),
    m("Hipcamp", "USA", "https://www.hipcamp.com", COM, "Book camping on private land", "Commission per booking",
      30, "Campsites are full; landowners have unused land.", note=VC, aud="B2C", czk=400, d=3, c=2, x=3, r=3, mo=3,
      cz="Czech wild-camping rules are strict, making legal private pitches attractive."),
    m("Outdoorsy", "USA", "https://www.outdoorsy.com", COM, "Peer-to-peer campervan & RV rental",
      "Commission per rental", 80, "Campervan owners leave them idle most of the year.", note=VC, aud="B2C",
      czk=1_500, sam=10_000, d=3, c=3, x=4, r=3, mo=2),
    m("Turo", "USA", "https://turo.com", COM, "Peer-to-peer car rental", "Commission per trip", 60,
      "Private cars sit idle 95% of the time.", note=VC, aud="B2C", czk=900, d=2, c=3, x=4, r=4, mo=2),
    m("Meetup", "USA", "https://www.meetup.com", COM, "Platform for local interest groups", "Organiser subscription",
      15, "People want to meet others with shared interests offline.", note="Category benchmark",
      aud="B2C", d=2, c=4, x=3, mo=1),
    m("Strava", "USA", "https://www.strava.com", COM, "Social network for runners & cyclists", "Freemium subscription",
      12, "Athletes want to track and share workouts.", note="Category benchmark; widely used in CZ",
      aud="B2C", d=2, c=5, x=5, mo=1),
    m("Kickstarter", "USA", "https://www.kickstarter.com", CRE, "Reward-based crowdfunding", "5% platform fee",
      100, "Creators need upfront funding to launch products.", note="Public-benefit company; benchmark",
      czk=1_500, sam=3_000, d=2, c=4, x=4, r=2, mo=2,
      comps=[("Hithit", "https://www.hithit.com", "Czech crowdfunding", True),
             ("Startovač", "https://www.startovac.cz", "Czech crowdfunding", True)]),
    m("ClassPass", "USA", "https://classpass.com", HEA, "One membership for many gyms & studios", "Monthly credits",
      49, "People want variety across fitness studios.", note="Acquired by Mindbody", aud="B2C", czk=990,
      d=2, c=5, x=4, mo=1, comps=[("MultiSport card", "https://www.multisport.cz", "Dominant employee-benefit pass", True)]),
    m("Going (Scott's Cheap Flights)", "USA", "https://www.going.com", CRE, "Cheap flight deal alerts",
      "Consumer subscription", 5, "Travellers miss rare airfare deals.", note="Bootstrapped to eight-figure revenue",
      aud="B2C", czk=99, d=3, c=4, x=2, mo=2,
      comps=[("Czech flight-deal sites", "", "Free, ad-funded (verify)", True)]),
    m("6AM City", "USA", "https://6amcity.com", CRE, "Local daily news newsletters", "Local advertising",
      500, "City residents lack a quick daily local news digest.", note=VC, czk=12_000, sam=300,
      d=3, c=2, x=2, mo=4, segs=["Local businesses advertising in Prague/Brno"],
      cz="Price is per advertiser-month. Hyper-local Czech newsletters (Prague districts, Brno) are underserved."),

    # ---------------------------------------------------------------- USA - e-commerce & D2C
    m("Klaviyo", "USA", "https://www.klaviyo.com", ECOM, "Email & SMS for e-commerce", "Subscription by contacts",
      45, "E-shops need segmentation based on purchase data.", note="Public", d=3, c=4, x=4, mo=2,
      comps=[("Ecomail", "https://ecomail.cz", "Czech e-shop email", True)]),
    m("Privy", "USA", "https://www.privy.com", ECOM, "Pop-ups & email capture for small e-shops",
      "Subscription SaaS", 30, "Small shops don't capture visitor emails.", note="Acquired by Attentive", d=2, c=3, x=2),
    m("BarkBox", "USA", "https://www.barkbox.com", D2C, "Monthly themed dog toys & treats box", "Subscription box",
      35, "Dog owners want new toys without shopping.", note="Public (BARK)", aud="B2C", czk=690, d=3, c=2, x=3, mo=3,
      cogs=0.55, cz="Czechia has one of the highest dog-ownership rates in the EU."),
    m("Dollar Shave Club", "USA", "https://www.dollarshaveclub.com", D2C, "Razor blade subscription",
      "Subscription", 10, "Razor blades are overpriced at retail.", note="Acquired by Unilever for $1B",
      aud="B2C", czk=199, d=2, c=4, x=3, mo=1, cogs=0.5),
    m("Warby Parker", "USA", "https://www.warbyparker.com", D2C, "Affordable D2C glasses with home try-on",
      "Product sales", 95, "Glasses are overpriced by optical chains.", note="Public", aud="B2C", czk=1_990,
      d=3, c=3, x=4, r=3, mo=2, cogs=0.4),
    m("Stitch Fix", "USA", "https://www.stitchfix.com", D2C, "Personal styling boxes", "Styling fee + purchases",
      100, "People hate shopping for clothes.", note="Public", aud="B2C", czk=1_500, d=2, c=2, x=4, mo=2, cogs=0.6),
    m("Rent the Runway", "USA", "https://www.renttherunway.com", D2C, "Designer clothing rental", "Subscription",
      100, "Designer outfits are expensive for one-off events.", note="Public", aud="B2C", czk=1_500,
      d=2, c=2, x=5, mo=2, cogs=0.5),
    m("Misfits Market", "USA", "https://www.misfitsmarket.com", D2C, "Discounted imperfect produce delivery",
      "Per-order", 50, "Edible 'ugly' produce gets wasted.", note=VC, aud="B2C", czk=900, d=2, c=4, x=5, mo=2,
      cogs=0.7, comps=[("Rohlík.cz", "https://www.rohlik.cz", "Dominant Czech online grocery", True)]),
    m("Liquid Death", "USA", "https://liquiddeath.com", D2C, "Canned water with irreverent branding", "Product sales",
      30, "Healthy drinks are marketed blandly.", note=VC, aud="B2C", czk=450, d=2, c=3, x=3, mo=2, cogs=0.5),
    m("Beardbrand", "USA", "https://www.beardbrand.com", D2C, "Beard-care products grown via YouTube",
      "Product sales", 30, "Men lack credible grooming advice and products.", note="Bootstrapped, content-led",
      aud="B2C", czk=450, d=2, c=3, x=2, mo=2, cogs=0.4),

    # ---------------------------------------------------------------- USA - hospitality & finance
    m("Toast", "USA", "https://pos.toasttab.com", HOS, "Restaurant POS, payroll and online ordering",
      "SaaS + payment processing", 110, "Restaurants run on disconnected legacy systems.", note="Public",
      czk=1_990, d=3, c=5, x=5, mo=1, comps=[("Dotykačka", "https://www.dotykacka.cz", "Czech POS", True),
                                             ("Storyous", "https://www.storyous.com", "Czech POS", True)]),
    m("Slice", "USA", "https://slicelife.com", HOS, "Online ordering for independent pizzerias",
      "Per-order fee", 80, "Independent pizzerias lose margin to big delivery apps.", note=VC, czk=990,
      sam=2_000, d=3, c=3, x=3, mo=3),
    m("PriceLabs", "USA", "https://hello.pricelabs.co", HOS, "Dynamic pricing for short-term rentals",
      "Subscription per listing", 20, "Hosts set prices by gut feeling and leave money on the table.",
      note="Bootstrapped", czk=390, sam=8_000, d=3, c=2, x=3, r=2, mo=2),
    m("AirDNA", "USA", "https://www.airdna.co", HOS, "Short-term rental market data", "Subscription SaaS",
      40, "Investors can't estimate Airbnb income for a flat.", note=VC, sam=3_000, d=2, c=2, x=3, r=2, mo=2),
    m("FareHarbor", "USA", "https://fareharbor.com", HOS, "Booking software for tours & activities",
      "Fee passed to customer", 50, "Tour operators take bookings by phone and email.", note="Acquired by Booking Holdings",
      sam=3_000, d=4, c=3, x=3, mo=3, segs=["Prague walking & food tours", "Boat & bike rentals", "Escape rooms"]),
    m("Rocket Money", "USA", "https://www.rocketmoney.com", FIN, "Cancel subscriptions & negotiate bills",
      "Freemium + % of savings", 8, "Consumers overpay for forgotten subscriptions and bills.",
      note="Acquired by Rocket Companies", aud="B2C", czk=129, d=3, c=2, x=4, r=2, mo=3,
      cz="Energy and telco price comparison is a big consumer topic in CZ."),
    m("YNAB", "USA", "https://www.ynab.com", FIN, "Zero-based budgeting app", "Consumer subscription",
      15, "People don't know where their money goes.", note="Bootstrapped", aud="B2C", czk=199, d=2, c=4, x=3, mo=2,
      comps=[("Wallet by BudgetBakers", "https://budgetbakers.com", "Brno-based budgeting app", True)]),
    m("LegalZoom", "USA", "https://www.legalzoom.com", FIN, "Online company formation & legal documents",
      "Per-document + subscription", 30, "Lawyers are too expensive for simple legal paperwork.", note="Public",
      czk=590, d=3, c=4, x=3, r=4, mo=3, comps=[("Legito", "https://www.legito.com", "Czech legal automation", True)]),
    m("HoneyBook", "USA", "https://www.honeybook.com", FIN, "Client management for creative freelancers",
      "Subscription SaaS", 36, "Photographers and planners juggle contracts, invoices and inquiries.", note=VC,
      sam=15_000, d=3, c=2, x=3, mo=2),
    m("Dubsado", "USA", "https://www.dubsado.com", FIN, "Business management for service providers",
      "Subscription SaaS", 40, "Service providers repeat the same admin for every client.", note=BOOT,
      sam=15_000, d=2, c=2, x=3, mo=2),
    m("Acuity Scheduling", "USA", "https://acuityscheduling.com", LOC, "Appointment booking for service businesses",
      "Subscription SaaS", 20, "Clients want to self-book appointments online.",
      note="Bootstrapped, acquired by Squarespace", d=3, c=5, x=2, mo=1,
      comps=[("Reservio", "https://www.reservio.cz", "Czech booking leader", True)]),

    # ---------------------------------------------------------------- USA - creators & media
    m("Teachable", "USA", "https://teachable.com", CRE, "Online course platform", "Subscription SaaS", 59,
      "Experts want to sell courses without tech hassle.", note="Acquired", d=3, c=4, x=3, mo=2),
    m("Kajabi", "USA", "https://kajabi.com", CRE, "All-in-one platform for knowledge businesses",
      "Subscription SaaS", 149, "Coaches stitch together many tools to sell programs.", note="Bootstrapped to $1B+ valuation",
      d=3, c=4, x=3, mo=2, comps=[("Mioweb", "https://www.mioweb.cz", "Czech course/web builder", True)]),
    m("Substack", "USA", "https://substack.com", CRE, "Paid newsletters for writers", "10% of subscriptions",
      50, "Writers want direct income from readers.", note=VC, czk=600, sam=3_000, d=2, c=4, x=4, mo=2,
      comps=[("HeroHero", "https://herohero.co", "Czech creator memberships", True)]),
    m("StreamYard", "USA", "https://streamyard.com", CRE, "Browser-based live-streaming studio", "Subscription SaaS",
      25, "Going live with guests needs complex software.", note="Bootstrapped, acquired by Hopin",
      d=2, c=3, x=4, mo=1),
    m("Tailwind Labs (Tailwind UI)", "Canada", "https://tailwindui.com", DEV, "Premium UI component kits",
      "One-time purchase", 25, "Developers want beautiful UI without a designer.",
      note="Bootstrapped; founder reported $M+ in sales", sam=2_000, d=1, c=3, x=3, mo=1),

    # ---------------------------------------------------------------- Canada
    m("Shopify", "Canada", "https://www.shopify.com", ECOM, "E-commerce platform for merchants",
      "Subscription + payments", 39, "Merchants need an online store without developers.", note="Public; category benchmark",
      d=3, c=5, x=5, mo=1, comps=[("Shoptet", "https://www.shoptet.cz", "Dominant Czech e-shop platform", True),
                                  ("Upgates", "https://www.upgates.cz", "Czech e-shop platform", True)]),
    m("Jobber", "Canada", "https://getjobber.com", LOC, "Quotes, scheduling & invoicing for home-service businesses",
      "Subscription SaaS", 69, "Cleaners, gardeners and plumbers run their business on paper.", note=VC,
      d=4, c=2, x=4, mo=3, segs=["Cleaning companies", "Gardeners", "Plumbers & electricians"]),
    m("Wave", "Canada", "https://www.waveapps.com", FIN, "Free accounting, paid payments & payroll",
      "Freemium, monetised by payments", 16, "Micro-businesses can't afford accounting software.",
      note="Acquired by H&R Block", d=3, c=5, x=4, r=3, mo=2,
      comps=[("iDoklad", "https://www.idoklad.cz", "Free Czech invoicing", True)]),
    m("FreshBooks", "Canada", "https://www.freshbooks.com", FIN, "Invoicing & accounting for freelancers",
      "Subscription SaaS", 19, "Freelancers struggle with invoicing and expenses.", note=VC, d=3, c=5, x=3, r=3,
      comps=[("Fakturoid", "https://www.fakturoid.cz", "Czech market leader", True)]),
    m("Thinkific", "Canada", "https://www.thinkific.com", CRE, "Course creation platform", "Subscription SaaS", 49,
      "Creators need to host and sell courses.", note="Public", d=3, c=4, x=3, mo=2),
    m("Fathom Analytics", "Canada", "https://usefathom.com", DEV, "Privacy-first website analytics",
      "Subscription SaaS", 15, "Site owners want analytics without cookie banners.", note=BOOT, d=3, c=3, x=4, mo=2),
    m("Clio", "Canada", "https://www.clio.com", FIN, "Practice management for law firms", "Subscription per user",
      49, "Small law firms run matters, time and billing in separate tools.", note=VC, sam=8_000,
      d=3, c=3, x=4, r=3, mo=3, segs=["Small law firms (advokátní kanceláře)", "Notaries", "Insolvency administrators"]),
    m("7shifts", "Canada", "https://www.7shifts.com", HOS, "Scheduling & tip management for restaurants",
      "Subscription per location", 35, "Restaurant managers spend hours on schedules.", note=VC,
      czk=790, d=4, c=2, x=3, r=3, mo=3),
    m("Smile.io", "Canada", "https://smile.io", ECOM, "Loyalty & rewards programs for e-shops",
      "App subscription", 49, "Small e-shops struggle with repeat purchases.", note=VC, d=3, c=3, x=2, mo=2),
    m("Obsidian", "Canada", "https://obsidian.md", DEV, "Local-first markdown notes", "Freemium + add-ons",
      8, "Knowledge workers want private, future-proof notes.", note="Bootstrapped by a tiny team", aud="B2C",
      d=1, c=4, x=4, mo=1),
    m("Spellbook", "Canada", "https://www.spellbook.legal", AI, "AI contract drafting inside Microsoft Word",
      "Subscription per lawyer", 100, "Lawyers spend hours drafting and redlining contracts.", note=VC,
      sam=8_000, d=3, c=2, x=4, r=3, mo=4, cz="Czech contract law and language need a local model/prompt layer."),
    m("Jane App", "Canada", "https://jane.app", HEA, "Booking, charting & billing for clinics", "Subscription SaaS",
      79, "Physio and wellness clinics juggle paper charts and phone bookings.", note=BOOT, sam=6_000,
      d=3, c=3, x=3, r=3, mo=3),

    # ---------------------------------------------------------------- Latin America
    m("Hotmart", "Brazil", "https://hotmart.com", CRE, "Platform for selling courses & digital products",
      "Commission on sales", 50, "Experts need payments, hosting and affiliates for info-products.",
      note="Brazilian leader; very large", czk=700, d=3, c=4, x=4, mo=2),
    m("RD Station", "Brazil", "https://www.rdstation.com", MKT, "Marketing automation for SMBs", "Subscription SaaS",
      50, "SMBs can't afford HubSpot but need automation.", note="Acquired by TOTVS", d=3, c=4, x=4, mo=2),
    m("Conta Azul", "Brazil", "https://contaazul.com", FIN, "Cloud management & accounting for small businesses",
      "Subscription SaaS", 40, "Small firms manage finances in spreadsheets.", note=VC, d=3, c=5, x=4, r=3),
    m("Nuvemshop (Tiendanube)", "Brazil", "https://www.nuvemshop.com.br", ECOM, "E-commerce platform for LatAm SMBs",
      "Subscription SaaS", 20, "Small brands need an affordable local-language store.", note=VC, d=2, c=5, x=5, mo=1),
    m("Olist", "Brazil", "https://olist.com", ECOM, "Lets small merchants sell on all marketplaces as one seller",
      "Subscription + commission", 60, "Small merchants can't meet marketplace requirements alone.", note=VC,
      d=3, c=3, x=4, mo=3, comps=[("BaseLinker", "https://base.com", "Popular in CEE", False)]),
    m("Pipefy", "Brazil", "https://www.pipefy.com", DEV, "No-code workflow automation", "Subscription per user",
      20, "Back-office processes run on email and spreadsheets.", note=VC, d=2, c=3, x=4, mo=1),
    m("Clip", "Mexico", "https://clip.mx", FIN, "Card readers for small merchants", "Per-transaction fee",
      15, "Small merchants can't accept cards affordably.", note=VC, d=2, c=5, x=5, r=4, mo=1,
      comps=[("SumUp", "https://www.sumup.com", "Widely used in CZ", False)]),
    m("QuintoAndar", "Brazil", "https://www.quintoandar.com.br", COM, "Rentals without deposits or guarantors",
      "Commission + guarantee fee", 60, "Renting requires large deposits and slow bureaucracy.", note=VC,
      aud="B2C", czk=800, d=3, c=3, x=5, r=4, mo=3,
      comps=[("Bezrealitky", "https://www.bezrealitky.cz", "Czech owner-direct rentals", True)]),
    m("Wellhub (Gympass)", "Brazil", "https://wellhub.com", HEA, "Corporate fitness & wellness benefit",
      "Per-employee subscription", 10, "Companies want one wellness benefit for all employees.", note=VC,
      d=2, c=5, x=5, mo=1, comps=[("MultiSport card", "https://www.multisport.cz", "Dominant employee benefit", True)]),
    m("Platzi", "Colombia", "https://platzi.com", EDU, "Online tech & business courses in Spanish",
      "Consumer subscription", 25, "Spanish speakers lack quality tech education.", note=VC, aud="B2C",
      d=3, c=3, x=4, mo=3),
    m("Omie", "Brazil", "https://www.omie.com.br", FIN, "Cloud ERP for small businesses", "Subscription SaaS",
      50, "SMBs outgrow spreadsheets but ERPs are complex.", note=VC, d=3, c=5, x=5, r=3),
    m("Asaas", "Brazil", "https://www.asaas.com", FIN, "Automated billing & payment collection", "Per-transaction fee",
      30, "SMBs chase customer payments manually.", note=VC, d=3, c=3, x=4, r=3, mo=3,
      cz="QR platba and automatic bank pairing are the Czech equivalents of Pix-based billing."),
    m("Melhor Envio", "Brazil", "https://melhorenvio.com.br", ECOM, "Discounted multi-carrier shipping for small e-shops",
      "Margin on shipping", 20, "Small shops pay retail shipping rates.", note="Acquired", d=3, c=5, x=3,
      comps=[("Balíkobot", "https://www.balikobot.cz", "Czech multi-carrier API", True)]),
    m("Descomplica", "Brazil", "https://descomplica.com.br", EDU, "Online prep for university entrance exams",
      "Consumer subscription", 15, "Students can't afford prep courses.", note=VC, aud="B2C", czk=249,
      d=4, c=3, x=3, mo=4, comps=[("Scio", "https://www.scio.cz", "Czech exam prep", True)]),
    m("Buk", "Chile", "https://www.buk.cl", DEV, "HR & payroll software for LatAm SMBs", "Subscription per employee",
      5, "Payroll and HR compliance are complex for SMBs.", note=VC, czk=2_490, d=3, c=4, x=5, r=5, mo=3),
    m("Workana", "Argentina", "https://www.workana.com", COM, "Freelance marketplace for Latin America",
      "Commission", 50, "LatAm companies need local-language freelancers.", note="Regional leader",
      czk=800, d=2, c=4, x=4, mo=2,
      comps=[("Na volné noze", "https://www.navolnenoze.cz", "Czech freelancer community", True)]),
    m("Crehana", "Peru", "https://www.crehana.com", EDU, "Online courses for creative & digital skills",
      "Consumer subscription", 15, "Professionals want job-ready digital skills.", note=VC, aud="B2C",
      d=2, c=3, x=3, mo=2),
]
