"""Proven business models from Asia, Oceania, the Middle East and Africa."""

from ._helpers import AI, COM, CRE, D2C, DEV, ECOM, EDU, FIN, HEA, HOS, LOC, MKT, m

VC = "VC-backed; proves the category"
BOOT = "Bootstrapped and profitable; revenue not public"

MODELS = [
    # ---------------------------------------------------------------- India
    m("Zoho", "India", "https://www.zoho.com", DEV, "Suite of 50+ business apps for SMBs", "Subscription per user",
      15, "SMBs need affordable CRM, mail and finance tools.", note="Bootstrapped to $1B+ revenue", d=3, c=4, x=5, mo=1),
    m("Freshworks", "India", "https://www.freshworks.com", DEV, "Help desk & CRM for SMBs", "Freemium subscription",
      18, "Growing teams need simple customer-service software.", note="Public", d=3, c=4, x=4, mo=1),
    m("Chargebee", "India", "https://www.chargebee.com", FIN, "Subscription billing & revenue management",
      "Subscription SaaS", 250, "Subscription businesses outgrow simple payment tools.", note=VC, sam=1_500,
      d=2, c=3, x=5, r=3, mo=1),
    m("BrowserStack", "India", "https://www.browserstack.com", DEV, "Cloud testing on real browsers & devices",
      "Subscription SaaS", 39, "Developers can't test on every device.", note="Bootstrapped to $4B valuation",
      sam=2_000, d=1, c=3, x=5, mo=1),
    m("VWO", "India", "https://vwo.com", MKT, "A/B testing & conversion optimisation", "Subscription SaaS",
      200, "Marketers guess which page version converts better.", note="Bootstrapped (Wingify)", sam=2_000,
      d=2, c=3, x=4, mo=1),
    m("Khatabook", "India", "https://khatabook.com", FIN, "Digital credit ledger for small shopkeepers",
      "Freemium", 3, "Shopkeepers track customer credit in paper notebooks.", note=VC, sam=30_000, d=1, c=2, x=3, mo=2,
      cz="Store credit is rare in CZ retail; low fit."),
    m("Meesho", "India", "https://www.meesho.com", COM, "Social commerce: resell products via WhatsApp",
      "Commission", 10, "Home-based resellers lack products and logistics.", note="Public", aud="B2C",
      d=1, c=3, x=5, mo=2),
    m("Urban Company", "India", "https://www.urbancompany.com", LOC, "Trained home-service professionals on demand",
      "Commission per job", 40, "Home services are unreliable and unstandardised.", note="Public", aud="B2C",
      czk=700, d=4, c=3, x=4, r=3, mo=2),
    m("Classplus", "India", "https://classplusapp.com", EDU, "White-label apps for tutors & coaching centres",
      "Subscription SaaS", 50, "Tutors can't afford their own branded app.", note=VC, sam=5_000, d=3, c=2, x=3, mo=3,
      segs=["Tutoring centres (doučovací centra)", "Language schools", "Independent tutors"]),
    m("Physics Wallah", "India", "https://www.pw.live", EDU, "Ultra-affordable exam prep via YouTube & app",
      "Low-cost course fees", 5, "Quality exam prep is unaffordable for most families.", note="Profitable unicorn",
      aud="B2C", czk=149, d=3, c=3, x=3, mo=4, cz="Czech angle: low-cost přijímačky/maturita prep built on a YouTube audience."),
    m("Rebel Foods", "India", "https://www.rebelfoods.com", HOS, "Multi-brand cloud-kitchen operator",
      "Food sales", 1000, "Launching restaurant brands needs costly locations.", note=VC, aud="B2C", czk=2_500,
      sam=30_000, d=3, c=3, x=5, r=3, mo=2, cogs=0.6),
    m("Country Delight", "India", "https://www.countrydelight.in", D2C, "Fresh milk & dairy subscription delivery",
      "Daily subscription", 30, "Consumers distrust the quality of store milk.", note=VC, aud="B2C", czk=900,
      d=2, c=3, x=5, r=3, mo=3, cogs=0.7,
      comps=[("Rohlík.cz", "https://www.rohlik.cz", "Czech online grocery", True)],
      cz="Czech farm-milk dispensers (mlékomaty) show demand for fresh local milk."),
    m("HealthifyMe", "India", "https://www.healthifyme.com", HEA, "Calorie tracking + AI & human nutrition coaches",
      "Consumer subscription", 20, "People fail diets without personal coaching.", note=VC, aud="B2C", czk=399,
      d=3, c=3, x=4, mo=3),
    m("Apna", "India", "https://apna.co", COM, "Job platform for blue- and grey-collar workers", "Employer fees",
      100, "Frontline workers can't find jobs online.", note=VC, czk=2_000, sam=5_000, d=3, c=3, x=4, r=2, mo=3,
      cz="Czech angle: warehouse, logistics and manufacturing hiring, incl. foreign workers."),
    m("InVideo", "India", "https://invideo.io", AI, "AI video creation from prompts", "Freemium subscription",
      25, "Making marketing videos needs editing skills.", note=VC, d=3, c=4, x=4, mo=2, cogs=0.2),
    m("MyGate", "India", "https://mygate.com", COM, "App for apartment communities: visitors, dues, notices",
      "Subscription per unit", 1, "Housing societies run security and dues on paper.", note=VC, czk=790,
      sam=40_000, d=3, c=3, x=3, r=2, mo=4, cz="Price per building. Czech SVJ/BD associations are the analogue."),
    m("Chai Point", "India", "https://chaipoint.com", HOS, "Tea cafés + tea dispensers for offices",
      "Retail + B2B", 300, "Offices want good hot drinks without a barista.", note=VC, czk=4_000, sam=3_000,
      d=2, c=3, x=4, r=2, mo=2, cogs=0.5),
    m("Pocket FM", "India", "https://www.pocketfm.com", CRE, "Serialised audio stories app", "Pay-per-episode",
      5, "Commuters want bite-size entertainment.", note=VC, aud="B2C", czk=99, d=2, c=2, x=4, mo=3,
      comps=[("Audiolibrix", "https://www.audiolibrix.com", "Czech audiobooks", True)]),

    # ---------------------------------------------------------------- South-East Asia & Bangladesh
    m("Dorik", "Bangladesh", "https://dorik.com", DEV, "No-code website builder with AI", "Subscription SaaS",
      15, "Small businesses want websites without developers.", note=BOOT, d=2, c=5, x=3, mo=1),
    m("Kopi Kenangan", "Indonesia", "https://kopikenangan.com", HOS, "App-first grab-and-go coffee chain",
      "Retail", 800, "Quality coffee is too expensive for daily buying.", note=VC, aud="B2C", czk=2_000, sam=30_000,
      d=3, c=3, x=4, r=2, mo=2, cogs=0.5),
    m("Kitabisa", "Indonesia", "https://kitabisa.com", COM, "Donation crowdfunding platform", "Tip-based",
      20, "People can't easily raise money for medical or social causes.", note=VC, czk=300,
      d=3, c=4, x=3, r=3, mo=2,
      comps=[("Donio", "https://www.donio.cz", "Czech donation crowdfunding", True),
             ("Darujme.cz", "https://www.darujme.cz", "Czech donation platform", True)]),
    m("ShopBack", "Singapore", "https://www.shopback.com", MKT, "Cashback rewards for online shopping",
      "Affiliate commissions", 5, "Shoppers want rewards across many stores.", note=VC, aud="B2C", d=2, c=4, x=4, mo=1,
      comps=[("Tipli", "https://www.tipli.cz", "Czech cashback portal", True)]),
    m("Ahrefs", "Singapore", "https://ahrefs.com", MKT, "SEO tools & backlink index", "Subscription SaaS",
      129, "Marketers need data on search rankings and backlinks.", note="Bootstrapped to $100M+ ARR",
      sam=3_000, d=3, c=3, x=5, mo=1),
    m("Sendy", "Singapore", "https://sendy.co", MKT, "Self-hosted newsletter app using Amazon SES",
      "One-time licence", 69, "Email platforms get expensive as lists grow.", note="Solo founder, bootstrapped",
      sam=2_000, d=1, c=3, x=2, mo=1),
    m("SleekFlow", "Hong Kong", "https://sleekflow.io", MKT, "WhatsApp & social commerce inbox",
      "Subscription SaaS", 99, "Sales via WhatsApp and Instagram DMs is chaotic.", note=VC, d=2, c=2, x=3, mo=2),
    m("TypingMind", "Vietnam", "https://www.typingmind.com", AI, "Better chat UI for LLM APIs (bring your own key)",
      "One-time licence", 40, "Power users want a better ChatGPT interface.", note="Solo founder with public revenue",
      sam=5_000, d=2, c=3, x=2, mo=1),
    m("ELSA Speak", "Vietnam", "https://elsaspeak.com", EDU, "AI English pronunciation coach", "Consumer subscription",
      12, "Learners lack pronunciation feedback.", note=VC, aud="B2C", d=3, c=2, x=4, mo=2),

    # ---------------------------------------------------------------- China / Hong Kong / Taiwan
    m("Luckin Coffee", "China", "https://www.luckincoffee.com", HOS, "App-only ordering coffee chain",
      "Retail", 1000, "Coffee shops are slow and expensive.", note="Public", aud="B2C", czk=2_000, sam=30_000,
      d=3, c=3, x=5, r=2, mo=2, cogs=0.5),
    m("Pop Mart", "China", "https://www.popmart.com", D2C, "Blind-box collectible designer toys", "Product sales",
      15, "Collectors want surprise and scarcity.", note="Public", aud="B2C", czk=350, d=2, c=2, x=4, mo=1, cogs=0.4),
    m("Youzan", "China", "https://www.youzan.com", ECOM, "SaaS for social-commerce stores", "Subscription SaaS",
      100, "Merchants want stores inside social apps.", note="Public (HK)", d=2, c=2, x=5, mo=2),
    m("Community group-buying (Xingsheng Youxuan archetype)", "China", "", COM,
      "Neighbourhood leaders aggregate grocery orders", "Commission", 20,
      "Groceries are cheaper when neighbours order together.", note="Huge in China; many failed at scale",
      aud="B2C", czk=300, d=1, c=1, x=4, r=2, mo=2),
    m("Live-stream shopping for small brands (Taobao Live archetype)", "China", "", MKT,
      "Sell products via live video shows", "Commission / service fee", 200,
      "Brands struggle to convert social audiences.", note="Proven at scale in China",
      czk=4_000, sam=3_000, d=2, c=1, x=3, mo=3, cz="Still nascent in CZ - first-mover niche."),
    m("AfterShip", "Hong Kong", "https://www.aftership.com", ECOM, "Branded shipment tracking for e-shops",
      "Subscription SaaS", 11, "Customers keep asking 'where is my order?'.", note=VC, d=3, c=3, x=3, mo=2),
    m("Lalamove", "Hong Kong", "https://www.lalamove.com", LOC, "On-demand van & motorbike delivery",
      "Commission", 50, "Small businesses need same-hour delivery.", note=VC, czk=800, d=3, c=3, x=4, r=3, mo=2,
      comps=[("Liftago", "https://www.liftago.com", "Czech courier & taxi app", True)]),
    m("Hahow", "Taiwan", "https://hahow.in", EDU, "Crowdfunded online courses", "Course sales",
      30, "Creators don't know if a course will sell.", note=VC, aud="B2C", czk=500, d=2, c=2, x=3, mo=2),

    # ---------------------------------------------------------------- Japan & Korea
    m("freee", "Japan", "https://www.freee.co.jp", FIN, "Cloud accounting & HR for small businesses",
      "Subscription SaaS", 20, "Paper-based bookkeeping wastes SMB time.", note="Public", d=3, c=5, x=4, r=3),
    m("SmartHR", "Japan", "https://smarthr.jp", DEV, "Digitised HR & labour paperwork", "Subscription per employee",
      5, "Onboarding and social-insurance forms are paper-heavy.", note=VC, czk=2_490, d=3, c=3, x=4, r=4, mo=4,
      cz="Czech ČSSZ/health-insurer paperwork is a similar pain; price per company."),
    m("Cookpad", "Japan", "https://cookpad.com", COM, "Recipe-sharing community", "Freemium subscription",
      3, "Home cooks want tried-and-tested recipes.", note="Public", aud="B2C", d=2, c=4, x=3, mo=2,
      comps=[("Toprecepty.cz", "https://www.toprecepty.cz", "Czech recipe community", True)]),
    m("Raksul", "Japan", "https://raksul.com", ECOM, "Printing marketplace using idle print-shop capacity",
      "Margin", 200, "Printing is expensive; print shops have idle machines.", note="Public", czk=4_000, sam=10_000,
      d=2, c=3, x=4, mo=2, cogs=0.6),
    m("Spacemarket", "Japan", "https://www.spacemarket.com", COM, "Hourly rental of rooms, venues & spaces",
      "Commission", 30, "People need a space for a few hours; owners have idle rooms.", note="Public",
      czk=500, d=3, c=2, x=3, r=2, mo=2),
    m("Kumon", "Japan", "https://www.kumon.com", EDU, "After-school maths & reading franchise", "Monthly tuition",
      100, "Children fall behind in basics.", note="Global franchise", aud="B2C", czk=1_500, d=3, c=3, x=3, mo=3,
      cogs=0.5),
    m("Karrot (Danggeun)", "South Korea", "https://www.karrotmarket.com", COM, "Hyperlocal second-hand marketplace",
      "Local advertising", 30, "Selling used items to neighbours is clunky.", note=VC, czk=500, d=2, c=5, x=4, mo=1,
      comps=[("Bazoš", "https://www.bazos.cz", "Dominant Czech classifieds", True)]),
    m("Class101", "South Korea", "https://class101.net", EDU, "Hobby classes shipped with material kits",
      "Subscription + kits", 20, "Hobbies are hard to start without materials and guidance.", note=VC, aud="B2C",
      czk=390, d=2, c=2, x=4, mo=2),
    m("Channel Talk", "South Korea", "https://channel.io", DEV, "Chat, CRM & phone for small businesses",
      "Subscription SaaS", 30, "SMBs need one tool for customer conversations.", note=VC, d=3, c=4, x=3, mo=1),
    m("Ohouse", "South Korea", "https://ohou.se", D2C, "Interior-inspiration community + furniture shop",
      "Commission", 50, "People can't buy what they see in interior photos.", note=VC, czk=1_000, d=2, c=3, x=4, mo=2),

    m("Timee", "Japan", "https://timee.co.jp", COM, "Spot-work app: hourly shifts without interviews",
      "Commission on wages", 800, "Businesses need staff for a few hours; workers want flexible gigs.", note="Public",
      czk=12_000, sam=3_000, d=4, c=3, x=4, r=4, mo=3, cz="Fits Czech brigády/DPP culture; labour-agency licence needed."),
    m("note", "Japan", "https://note.com", CRE, "Blogging platform with paid posts & memberships",
      "Commission", 30, "Writers want to monetise individual articles.", note="Public", czk=500, sam=5_000,
      d=2, c=3, x=4, mo=2),
    m("Mercari", "Japan", "https://www.mercari.com", COM, "Mobile flea-market app", "Seller commission",
      5, "Selling used items is slow and awkward.", note="Public; category benchmark", aud="B2C", czk=60,
      d=3, c=5, x=5, mo=1, comps=[("Vinted", "https://www.vinted.cz", "Dominant in CZ", False),
                                  ("Bazoš", "https://www.bazos.cz", "Czech classifieds", True)]),
    m("Soomgo", "South Korea", "https://soomgo.com", LOC, "Marketplace for lessons, repairs & services",
      "Pay-per-quote", 20, "Customers can't compare local service providers.", note=VC, czk=400,
      d=3, c=4, x=3, mo=2),
    m("Kurly", "South Korea", "https://www.kurly.com", D2C, "Premium early-morning grocery delivery",
      "Product sales", 200, "Fresh premium groceries are hard to get before work.", note="Large Korean player",
      aud="B2C", czk=3_000, sam=30_000, d=2, c=5, x=5, r=3, mo=1, cogs=0.7,
      comps=[("Rohlík.cz", "https://www.rohlik.cz", "Dominant Czech online grocery", True)]),
    m("Pinkoi", "Taiwan", "https://www.pinkoi.com", COM, "Marketplace for independent designers", "Commission",
      20, "Independent designers lack reach.", note=VC, czk=300, d=2, c=4, x=4, mo=2,
      comps=[("Fler.cz", "https://www.fler.cz", "Czech handmade marketplace", True)]),
    m("iCHEF", "Taiwan", "https://www.ichefpos.com", HOS, "iPad POS for small restaurants", "Subscription SaaS",
      40, "Small restaurants need affordable, simple POS.", note=VC, czk=890, d=3, c=5, x=4, mo=1),
    m("Cars24", "India", "https://www.cars24.com", COM, "Instant used-car selling & buying", "Margin on resale",
      300, "Selling a used car privately is slow and risky.", note=VC, aud="B2C", czk=5_000, sam=10_000,
      d=3, c=4, x=5, r=3, mo=2, comps=[("AAA Auto", "https://www.aaaauto.cz", "Largest Czech used-car dealer", True)]),
    m("PolicyBazaar", "India", "https://www.policybazaar.com", FIN, "Insurance comparison marketplace",
      "Commission from insurers", 300, "Consumers can't compare insurance policies.", note="Public",
      czk=6_000, sam=300, d=2, c=4, x=4, r=5, mo=2,
      comps=[("Srovnejto.cz", "https://www.srovnejto.cz", "Czech insurance comparison", True)]),
    m("Lenskart", "India", "https://www.lenskart.com", D2C, "Omnichannel affordable eyewear", "Product sales",
      40, "Eyewear is expensive and inconvenient to buy.", note="Large, profitable", aud="B2C", czk=1_500,
      d=3, c=3, x=5, r=3, mo=2, cogs=0.4),
    m("NoBroker", "India", "https://www.nobroker.in", COM, "Brokerage-free property rentals", "Subscription plans",
      30, "Brokers charge high fees to renters and owners.", note=VC, aud="B2C", czk=700, d=3, c=5, x=4, r=3,
      comps=[("Bezrealitky", "https://www.bezrealitky.cz", "Czech owner-direct rentals", True)]),
    m("BukuWarung", "Indonesia", "https://bukuwarung.com", FIN, "Bookkeeping & payments app for micro-merchants",
      "Freemium + payments", 3, "Micro-merchants keep records on paper.", note=VC, sam=30_000, d=1, c=3, x=3, r=3, mo=1),
    m("respond.io", "Malaysia", "https://respond.io", MKT, "Unified messaging inbox (WhatsApp, IG, FB)",
      "Subscription SaaS", 79, "Teams lose customers across messaging channels.", note=VC, d=3, c=3, x=3, mo=2),
    m("Kalibrr", "Philippines", "https://www.kalibrr.com", COM, "Job platform with skills assessments",
      "Employer fees", 150, "Employers can't screen many applicants.", note=VC, czk=3_000, sam=3_000,
      d=2, c=5, x=4, mo=1, comps=[("Jobs.cz", "https://www.jobs.cz", "Czech market leader", True)]),
    m("Wongnai", "Thailand", "https://www.wongnai.com", HOS, "Restaurant reviews + POS for restaurants",
      "Ads + SaaS", 60, "Diners need trusted reviews; restaurants need tools.", note="Merged with LINE MAN",
      czk=1_200, d=2, c=4, x=4, mo=2, comps=[("Restu", "https://www.restu.cz", "Czech restaurant guide", True)]),

    # ---------------------------------------------------------------- Australia & New Zealand
    m("Canva", "Australia", "https://www.canva.com", DEV, "Easy graphic design for everyone", "Freemium subscription",
      15, "Non-designers need professional graphics.", note="Category benchmark", d=3, c=5, x=5, mo=1),
    m("Linktree", "Australia", "https://linktr.ee", CRE, "Link-in-bio pages", "Freemium subscription", 5,
      "Social profiles allow only one link.", note=VC, aud="B2C", d=2, c=4, x=2, mo=1),
    m("Airtasker", "Australia", "https://www.airtasker.com", LOC, "Marketplace for everyday tasks",
      "Service fees", 30, "Finding help for small jobs is hard.", note="Public (ASX)", aud="B2C", czk=500,
      d=3, c=3, x=4, r=3, mo=2),
    m("Envato", "Australia", "https://www.envato.com", CRE, "Marketplace & subscription for digital assets",
      "Subscription + commission", 16, "Creators need templates, fonts and stock.", note="Bootstrapped, acquired by Shutterstock",
      d=2, c=5, x=4, mo=1),
    m("SafetyCulture", "Australia", "https://safetyculture.com", DEV, "Mobile inspections & checklists",
      "Freemium per user", 24, "Inspections are done on paper clipboards.", note=VC, d=3, c=2, x=3, r=2, mo=2),
    m("Who Gives A Crap", "Australia", "https://www.whogivesacrap.org", D2C, "Eco toilet paper subscription donating profits",
      "Subscription", 40, "Everyday products lack sustainable, purpose-driven options.", note="Profitable B Corp",
      aud="B2C", czk=690, d=3, c=3, x=3, mo=2, cogs=0.6),
    m("Frank Body", "Australia", "https://www.frankbody.com", D2C, "Coffee body scrub built on Instagram",
      "Product sales", 15, "Skincare brands feel impersonal.", note="Bootstrapped", aud="B2C", czk=390,
      d=2, c=4, x=2, mo=1, cogs=0.4),
    m("Buildxact", "Australia", "https://www.buildxact.com", DEV, "Estimating & job software for small builders",
      "Subscription SaaS", 149, "Small builders price jobs in spreadsheets and lose margin.", note=VC, sam=8_000,
      d=3, c=2, x=4, mo=3),
    m("Cliniko", "Australia", "https://www.cliniko.com", HEA, "Practice management for allied-health clinics",
      "Subscription SaaS", 45, "Clinics need booking, notes and invoicing in one place.", note=BOOT, sam=6_000,
      d=3, c=3, x=3, r=3, mo=2),
    m("Fastmail", "Australia", "https://www.fastmail.com", DEV, "Private, ad-free email hosting", "Subscription per user",
      5, "Free email monetises your data.", note="Independent, profitable", d=2, c=4, x=4, r=2, mo=1),
    m("99designs", "Australia", "https://99designs.com", CRE, "Design contests & freelance designers",
      "Commission", 300, "Small businesses need logos without an agency.", note="Bootstrapped origins, acquired by Vista",
      czk=6_000, sam=2_000, d=2, c=4, x=3, mo=1),
    m("Xero", "New Zealand", "https://www.xero.com", FIN, "Cloud accounting for small businesses",
      "Subscription SaaS", 30, "Desktop accounting is clunky.", note="Public; category benchmark", d=3, c=5, x=5, r=3,
      comps=[("Pohoda", "https://www.stormware.cz", "Dominant Czech accounting software", True)]),
    m("Hnry", "New Zealand", "https://hnry.co.nz", FIN, "Automatic tax & accounting for sole traders (1% fee)",
      "% of income", 50, "Sole traders hate tax admin.", note=VC, czk=990, d=3, c=3, x=4, r=4, mo=4,
      cz="Czech analogue: automate paušální daň registration, payments and annual paperwork for OSVČ."),
    m("Crimson Education", "New Zealand", "https://www.crimsoneducation.org", EDU,
      "Admissions consulting for top foreign universities", "Package fees", 500, "Families want admission to elite universities.",
      note=VC, aud="B2C", czk=10_000, sam=3_000, d=2, c=2, x=3, mo=3),

    # ---------------------------------------------------------------- Middle East & Africa
    m("Instabug", "Egypt", "https://www.instabug.com", DEV, "In-app bug reporting & crash analytics",
      "Subscription SaaS", 249, "Mobile teams can't reproduce user-reported bugs.", note=VC, sam=800, d=1, c=3, x=4, mo=1),
    m("Money Fellows", "Egypt", "https://www.moneyfellows.com", FIN, "Digital rotating savings circles",
      "Fees per circle", 3, "Informal savings circles lack trust and structure.", note=VC, aud="B2C",
      d=1, c=1, x=4, r=5, mo=2),
    m("Kitopi", "UAE", "https://www.kitopi.com", HOS, "Cloud kitchens operated for restaurant brands",
      "Revenue share", 2000, "Brands want delivery reach without opening kitchens.", note=VC, czk=40_000,
      sam=300, d=2, c=2, x=5, r=3, mo=2),
    m("Foodics", "Saudi Arabia", "https://www.foodics.com", HOS, "Cloud restaurant POS & management",
      "Subscription SaaS", 60, "Restaurants run on legacy POS systems.", note=VC, czk=1_490, d=3, c=5, x=5, mo=1),
    m("Yoco", "South Africa", "https://www.yoco.com", FIN, "Card machines & payments for small merchants",
      "Per-transaction fee", 15, "Small merchants can't accept cards affordably.", note=VC, d=2, c=5, x=5, r=4, mo=1),
    m("SweepSouth", "South Africa", "https://sweepsouth.com", LOC, "Online booking of home cleaners",
      "Commission", 40, "Finding trusted domestic cleaners is hard.", note=VC, aud="B2C", czk=600,
      d=4, c=3, x=3, r=3, mo=2),
    m("GetSmarter", "South Africa", "https://www.getsmarter.com", EDU, "University-branded online short courses",
      "Course fees", 500, "Professionals want credentials without leaving work.", note="Acquired by 2U", aud="B2C",
      czk=10_000, sam=5_000, d=2, c=3, x=4, r=2, mo=2),
    m("Bumpa", "Nigeria", "https://www.getbumpa.com", ECOM, "Inventory & sales app for social sellers",
      "Subscription SaaS", 10, "Instagram and WhatsApp sellers track orders in notebooks.", note=VC, d=2, c=2, x=3, mo=2),
    m("M-KOPA", "Kenya", "https://www.m-kopa.com", FIN, "Pay-as-you-go financing for phones & solar kits",
      "Daily micro-payments", 5, "Low-income customers can't afford devices upfront.", note=VC, aud="B2C",
      d=1, c=2, x=5, r=5, mo=1),
    m("YouCan", "Morocco", "https://youcan.shop", ECOM, "E-commerce platform with cash-on-delivery focus",
      "Subscription SaaS", 20, "Sellers in cash-heavy markets need COD-friendly stores.", note="Moroccan market leader",
      d=2, c=5, x=4, mo=1, cz="Cash on delivery (dobírka) is still common in CZ - but Shoptet covers it."),
    m("Justlife", "UAE", "https://www.justlife.com", LOC, "Home cleaning & wellness services app",
      "Service margin", 60, "Booking reliable home services is inconvenient.", note=VC, aud="B2C", czk=700,
      d=3, c=3, x=4, r=3, mo=2),
    m("Eden Life", "Nigeria", "https://ouredenlife.com", LOC, "Home-management subscription (food, cleaning, laundry)",
      "Monthly subscription", 150, "Busy professionals juggle many domestic providers.", note=VC, aud="B2C",
      czk=5_000, sam=10_000, d=2, c=2, x=4, r=3, mo=2, cogs=0.6),
]
