"""Proven business models from Russia, Ukraine, CEE, the Baltics, Balkans, Turkey, Israel and Central Asia."""

from ._helpers import AI, COM, CRE, D2C, DEV, ECOM, EDU, FIN, HEA, HOS, LOC, MKT, m

VC = "VC-backed; proves the category"
BOOT = "Bootstrapped and profitable; revenue not public"
RU = "Leading Russian player; revenue not public"

MODELS = [
    # ---------------------------------------------------------------- Russia
    m("Tilda", "Russia", "https://tilda.cc", DEV, "Block-based website builder", "Subscription SaaS", 10,
      "Small businesses need good-looking sites without designers.", note=RU, d=2, c=5, x=4, mo=1,
      comps=[("Webnode", "https://www.webnode.cz", "Czech website builder", True)]),
    m("amoCRM (Kommo)", "Russia", "https://www.amocrm.ru", MKT, "Sales CRM centred on messenger chats",
      "Subscription per user", 15, "Leads arrive via WhatsApp/Telegram and get lost.", note=RU, d=3, c=4, x=3, mo=2,
      comps=[("Raynet", "https://raynet.cz", "Czech CRM", True)]),
    m("Bitrix24", "Russia", "https://www.bitrix24.ru", DEV, "All-in-one CRM, tasks & intranet", "Freemium subscription",
      50, "SMBs use many disconnected tools for sales and projects.", note=RU, d=2, c=4, x=5, mo=1),
    m("MoySklad (МойСклад)", "Russia", "https://www.moysklad.ru", FIN, "Cloud inventory & retail management",
      "Subscription SaaS", 20, "Small shops track stock in spreadsheets.", note=RU, d=3, c=4, x=4, r=2, mo=2,
      comps=[("Money S3 / Pohoda stock modules", "", "Accountant-centric", True)]),
    m("Evotor (Эвотор)", "Russia", "https://evotor.ru", FIN, "Smart cash registers with an app store",
      "Hardware + app subscriptions", 20, "Small retailers need compliant tills plus simple business apps.",
      note=RU, czk=450, d=2, c=4, x=5, r=4, mo=2,
      cz="Czech EET was abolished; a revival of electronic sales records has been discussed (verify)."),
    m("iiko", "Russia", "https://iiko.ru", HOS, "Restaurant management & POS", "Subscription per venue",
      80, "Restaurants need stock, kitchen and front-of-house in one system.", note=RU, czk=1_990,
      d=3, c=5, x=5, mo=1, comps=[("Dotykačka", "https://www.dotykacka.cz", "Czech POS", True)]),
    m("YCLIENTS", "Russia", "https://www.yclients.com", LOC, "Online booking & CRM for salons", "Subscription SaaS",
      25, "Salons manage bookings by phone and paper.", note=RU, d=3, c=5, x=3, mo=1,
      comps=[("Reservio", "https://www.reservio.cz", "Czech booking leader", True)]),
    m("DIKIDI", "Russia", "https://dikidi.ru", LOC, "Free booking app for beauty masters + marketplace",
      "Freemium", 10, "Independent beauty masters can't afford booking software.", note=RU,
      d=3, c=4, x=3, mo=2, segs=["Independent hairdressers & nail artists", "Lash & brow studios"]),
    m("Kontur.Elba (Контур.Эльба)", "Russia", "https://kontur.ru/elba", FIN, "Online accounting for sole proprietors",
      "Annual subscription", 15, "Sole proprietors fear tax reporting.", note=RU, d=3, c=5, x=4, r=4,
      comps=[("Fakturoid", "https://www.fakturoid.cz", "Czech leader", True)],
      cz="In CZ most OSVČ on paušální daň need little bookkeeping - demand is lower."),
    m("Knopka (Кнопка)", "Russia", "https://knopka.com", FIN, "Outsourced accounting by subscription",
      "Monthly subscription", 150, "Small firms can't find reliable accountants.", note=RU, czk=3_500,
      d=3, c=3, x=3, r=3, mo=3, cogs=0.5),
    m("Diadoc (Диадок)", "Russia", "https://www.diadoc.ru", FIN, "Electronic invoices & document exchange (EDI)",
      "Per-document fees", 20, "Paper invoices and acts slow down B2B payments.", note=RU, d=3, c=3, x=4, r=3, mo=3,
      cz="EU e-invoicing (ViDA) and the ISDOC format make B2B e-invoicing a growing Czech topic."),
    m("Solar Staff", "Russia", "https://solar-staff.com", FIN, "Payouts & paperwork for freelance contractors",
      "% of payouts", 100, "Companies struggle to pay many freelancers legally.", note=RU, sam=3_000,
      d=2, c=2, x=4, r=4, mo=3, cz="Watch švarcsystém rules when paying OSVČ contractors long-term."),
    m("Unisender", "Russia", "https://www.unisender.com", MKT, "Email & SMS marketing", "Subscription by contacts",
      15, "SMBs need affordable email campaigns.", note=RU, d=3, c=5, x=4, mo=1,
      comps=[("Ecomail", "https://ecomail.cz", "Czech email marketing", True)]),
    m("Roistat", "Russia", "https://roistat.com", MKT, "End-to-end marketing analytics (ad spend to revenue)",
      "Subscription SaaS", 100, "Businesses can't tie ad spend to actual sales.", note=RU, sam=3_000,
      d=3, c=2, x=4, r=2, mo=3),
    m("Calltouch", "Russia", "https://www.calltouch.ru", MKT, "Call tracking & lead analytics", "Subscription SaaS",
      60, "Businesses don't know which ads make the phone ring.", note=RU, sam=5_000, d=3, c=2, x=4, r=2, mo=3,
      segs=["Car dealers", "Clinics", "Real-estate developers"]),
    m("Jivo", "Russia", "https://www.jivo.ru", DEV, "Omnichannel live chat & messenger inbox",
      "Subscription per agent", 20, "Small businesses miss website and messenger inquiries.", note=RU,
      d=3, c=4, x=3, mo=1, comps=[("Smartsupp", "https://www.smartsupp.com", "Czech live chat", True)]),
    m("MPStats", "Russia", "https://mpstats.io", ECOM, "Analytics for Wildberries & Ozon sellers", "Subscription SaaS",
      50, "Marketplace sellers can't see competitors' sales and prices.", note=RU, sam=5_000, d=3, c=2, x=4, mo=3,
      segs=["Allegro.cz & Kaufland.cz sellers", "Heureka merchants"],
      cz="Czech analogue: sales & price intelligence for Allegro, Kaufland and Heureka."),
    m("Retail Rocket", "Russia", "https://retailrocket.ru", ECOM, "Product recommendations & personalisation",
      "Subscription / % of revenue", 200, "E-shops show every visitor the same products.", note=RU,
      sam=3_000, d=3, c=3, x=4, mo=2),
    m("Ecwid", "Russia", "https://www.ecwid.com", ECOM, "Embeddable online store widget",
      "Freemium subscription", 15, "Site owners want to add a shop to an existing website.",
      note="Russian-founded, acquired by Lightspeed", d=2, c=5, x=4, mo=1),
    m("Marketplace fulfilment operator (Wildberries/Ozon sellers)", "Russia", "", ECOM,
      "Warehousing, labelling and delivery to marketplaces for small sellers", "Per-unit fees", 300,
      "Small sellers can't meet marketplaces' packaging and delivery rules.", note="Very common Russian SMB model",
      czk=6_000, sam=3_000, d=3, c=3, x=4, r=2, mo=3,
      cz="Czech analogue: fulfilment for Allegro, Kaufland, Alza marketplace and Heureka sellers."),
    m("Flowwow", "Russia", "https://flowwow.com", COM, "Marketplace for local florists & gift shops",
      "Commission", 30, "Customers can't easily order from independent local florists.", note=RU, czk=500,
      d=3, c=3, x=3, mo=3),
    m("Profi.ru", "Russia", "https://profi.ru", LOC, "Marketplace for tutors, repairs & beauty specialists",
      "Pay-per-lead", 30, "People struggle to find vetted local specialists.", note=RU, czk=600,
      d=3, c=4, x=4, mo=2, comps=[("Nejřemeslníci.cz", "https://www.nejremeslnici.cz", "Czech craftsman marketplace", True)]),
    m("Kukhnya na Rayone (Кухня на районе)", "Russia", "", HOS, "Dark-kitchen delivery brand with own logistics",
      "Food sales", 1000, "Home-style food delivery is slow and expensive.", note=RU, aud="B2C", czk=2_500,
      sam=30_000, d=3, c=4, x=5, r=3, mo=2, cogs=0.6),
    m("Dodo Pizza", "Russia", "https://dodopizza.ru", HOS, "Tech-driven pizza franchise with open financials",
      "Franchise royalties", 3000, "Franchisees lack tech and data to run delivery efficiently.",
      note="Famous for publishing its financials openly", aud="B2C", czk=2_000, sam=30_000,
      d=3, c=4, x=5, r=3, mo=2, cogs=0.65),
    m("VkusVill (ВкусВилл)", "Russia", "https://vkusvill.ru", D2C, "Fresh own-brand health-food store chain",
      "Retail", 200, "Shoppers want fresh, short-shelf-life healthy food.", note="Large Russian retailer",
      aud="B2C", czk=2_500, sam=40_000, d=2, c=4, x=5, r=3, mo=2, cogs=0.7,
      comps=[("Rohlík.cz", "https://www.rohlik.cz", "Czech online grocery", True)]),
    m("Skyeng", "Russia", "https://skyeng.ru", EDU, "Online English school with own platform",
      "Lesson packages", 100, "Adults want flexible English lessons with a teacher.", note=RU, aud="B2C",
      czk=2_000, d=3, c=4, x=4, mo=2, cogs=0.5),
    m("GetCourse", "Russia", "https://getcourse.ru", CRE, "Platform for online schools & info-businesses",
      "Subscription SaaS", 60, "Online schools juggle payments, courses and email.", note=RU, d=3, c=4, x=4, mo=2,
      comps=[("Mioweb", "https://www.mioweb.cz", "Czech course builder", True)]),
    m("Uchi.ru (Учи.ру)", "Russia", "https://uchi.ru", EDU, "Interactive school maths & language exercises",
      "Freemium for parents", 10, "Children lose interest in practice worksheets.", note=RU, aud="B2C", czk=199,
      d=3, c=3, x=4, mo=4, comps=[("Umíme to", "https://www.umimeto.org", "Czech adaptive practice", True)]),
    m("Foxford (Фоксфорд)", "Russia", "https://foxford.ru", EDU, "Online school for exam preparation",
      "Course packages", 60, "Students need structured prep for final exams.", note=RU, aud="B2C", czk=990,
      d=3, c=3, x=4, mo=4, comps=[("Scio", "https://www.scio.cz", "Czech exam prep", True)]),
    m("iSpring", "Russia", "https://www.ispring.ru", EDU, "E-learning authoring & corporate LMS",
      "Subscription SaaS", 100, "Companies struggle to build and track employee training.", note=RU,
      sam=3_000, d=2, c=3, x=4, mo=2),
    m("LitRes (ЛитРес)", "Russia", "https://www.litres.ru", CRE, "E-books, audiobooks & self-publishing",
      "Sales + subscription", 10, "Readers want instant digital books; authors want to self-publish.", note=RU,
      aud="B2C", czk=199, d=2, c=4, x=4, mo=2,
      comps=[("Palmknihy", "https://www.palmknihy.cz", "Czech e-book store", True),
             ("Audiolibrix", "https://www.audiolibrix.com", "Czech audiobooks", True)]),
    m("Telega.in", "Russia", "https://telega.in", MKT, "Marketplace for Telegram channel ads", "Commission",
      100, "Advertisers can't buy Telegram channel ads safely.", note=RU, sam=500, d=1, c=1, x=3, mo=2,
      cz="Telegram is niche in CZ; included as a low-fit example."),
    m("Senler", "Russia", "https://senler.ru", MKT, "Mailing & automation for VK communities", "Subscription SaaS",
      10, "VK community admins can't message subscribers at scale.", note=RU, sam=500, d=1, c=1, x=3, mo=1,
      cz="VK is not used in CZ; the Czech analogue would target Instagram/WhatsApp."),
    m("Salebot", "Russia", "https://salebot.pro", MKT, "Chatbot builder for messengers", "Subscription SaaS",
      20, "Small businesses want automated sales chats in messengers.", note=RU, d=2, c=2, x=3, mo=2),
    m("Taplink", "Russia", "https://taplink.ru", CRE, "Link-in-bio mini-sites with payments", "Freemium subscription",
      3, "Instagram sellers need a mini-site with a catalogue and payments.", note=RU, aud="B2C", czk=79,
      d=2, c=3, x=2, mo=1),
    m("Huntflow (Хантфлоу)", "Russia", "https://huntflow.ru", DEV, "Applicant tracking for recruiters",
      "Subscription per recruiter", 60, "Recruiters manage candidates in spreadsheets.", note=RU, d=3, c=4, x=3, mo=2,
      comps=[("Recruitis", "https://recruitis.io", "Czech ATS", True)]),
    m("Banki.ru", "Russia", "https://www.banki.ru", FIN, "Comparison marketplace for loans, cards & deposits",
      "Lead fees from banks", 500, "Consumers can't compare financial products easily.", note=RU,
      czk=10_000, sam=300, d=2, c=4, x=4, r=4, mo=2,
      comps=[("Finparáda", "https://www.finparada.cz", "Czech comparison site", True)]),
    m("Invitro", "Russia", "https://www.invitro.ru", HEA, "Lab tests without referral, ordered online",
      "Per-test", 30, "Patients wait weeks for a referral to get simple tests.", note=RU, aud="B2C", czk=990,
      d=3, c=3, x=5, r=5, mo=2),
    m("Aviasales", "Russia", "https://www.aviasales.ru", HOS, "Flight metasearch", "Affiliate commissions",
      10, "Travellers can't find the cheapest flights.", note="Bootstrapped origin; large", aud="B2C",
      d=2, c=5, x=5, mo=1, comps=[("Kiwi.com", "https://www.kiwi.com", "Brno-based global travel platform", True)]),
    m("2GIS", "Russia", "https://2gis.ru", COM, "City directory with offline maps", "Local business advertising",
      100, "People need up-to-date business info and maps.", note=RU, czk=2_000, sam=3_000, d=1, c=5, x=5, mo=1,
      comps=[("Firmy.cz + Mapy.com", "https://www.firmy.cz", "Seznam directory & maps", True)]),
    m("Travelline", "Russia", "https://www.travelline.ru", HOS, "Booking engine & channel manager for small hotels",
      "Subscription + commission", 60, "Small hotels pay high OTA commissions.", note=RU, d=3, c=4, x=4, r=2, mo=2,
      comps=[("Previo", "https://www.previo.cz", "Czech hotel system", True)]),
    m("Aspro", "Russia", "https://aspro.ru", DEV, "Ready-made website & e-shop templates", "One-time + support",
      100, "Small businesses want a professional site fast.", note=RU, czk=5_000, sam=3_000, d=2, c=3, x=2, mo=2,
      cz="Czech analogue: premium Shoptet templates and themes."),

    # ---------------------------------------------------------------- Ukraine & Belarus
    m("Grammarly", "Ukraine", "https://www.grammarly.com", AI, "AI writing assistant", "Freemium subscription",
      12, "People make embarrassing mistakes in English writing.", note="Founded in Kyiv; very large",
      aud="B2C", d=3, c=3, x=5, mo=3, cz="A Czech-language grammar & style assistant is a real gap."),
    m("MacPaw", "Ukraine", "https://macpaw.com", DEV, "Mac utilities (CleanMyMac)", "Subscription / one-time",
      4, "Macs slow down and fill with junk.", note="Bootstrapped", aud="B2C", d=1, c=4, x=4, mo=1),
    m("Poster POS", "Ukraine", "https://joinposter.com", HOS, "Cloud POS for cafés & small restaurants",
      "Subscription SaaS", 30, "Small cafés need an affordable POS on a tablet.", note="Bootstrapped", czk=690,
      d=3, c=5, x=4, mo=1, comps=[("Dotykačka", "https://www.dotykacka.cz", "Czech POS", True)]),
    m("Checkbox", "Ukraine", "https://checkbox.ua", FIN, "Software cash register (fiscalisation via app)",
      "Subscription", 10, "Small merchants need cheap legally compliant receipts.", note="Ukrainian market leader",
      d=1, c=1, x=4, r=5, mo=2, cz="No Czech fiscal requirement today; relevant only if e-sales records return."),
    m("KeyCRM", "Ukraine", "https://keycrm.app", ECOM, "CRM for online & Instagram sellers", "Subscription SaaS",
      20, "Social sellers take orders in DMs and lose track.", note="Bootstrapped", d=3, c=2, x=3, mo=2),
    m("SendPulse", "Ukraine", "https://sendpulse.com", MKT, "Email, SMS & chatbot marketing platform",
      "Freemium subscription", 20, "SMBs need multichannel marketing in one tool.", note=BOOT, d=3, c=4, x=4, mo=1),
    m("Crowdin", "Ukraine", "https://crowdin.com", DEV, "Software localisation management", "Subscription SaaS",
      60, "Translating apps and websites is chaotic.", note=BOOT, sam=1_500, d=2, c=2, x=4, mo=1),
    m("Readdle", "Ukraine", "https://readdle.com", DEV, "Productivity apps (Spark mail, Documents)",
      "Freemium subscription", 5, "Mobile professionals need better mail and document apps.", note=BOOT,
      aud="B2C", d=1, c=4, x=4, mo=1),
    m("Laba", "Ukraine", "https://laba.ua", EDU, "Online courses for business professionals",
      "Course fees", 150, "Professionals want practical, career-focused courses.", note="Ukrainian market leader",
      aud="B2C", czk=500, sam=20_000, d=3, c=3, x=3, mo=3,
      cz="~3,000 CZK courses bought roughly twice a year, shown as a ~500 CZK monthly equivalent."),
    m("BetterMe", "Ukraine", "https://betterme.world", HEA, "Fitness & diet app", "Consumer subscription",
      15, "People want personalised home workouts and meal plans.", note="Large, profitable", aud="B2C",
      d=2, c=4, x=4, mo=1),
    m("Jooble", "Ukraine", "https://jooble.org", COM, "Job-search aggregator", "Pay-per-click from job boards",
      100, "Job seekers must search many job sites.", note="Bootstrapped, global", czk=2_000, sam=1_000,
      d=2, c=5, x=4, mo=1, comps=[("Jobs.cz", "https://www.jobs.cz", "Czech market leader", True)]),
    m("Depositphotos", "Ukraine", "https://depositphotos.com", CRE, "Stock photo & video marketplace",
      "Subscription + credits", 30, "Businesses need affordable licensed imagery.", note="Acquired by VistaPrint",
      d=2, c=5, x=4, mo=1),
    m("Flo", "Belarus", "https://flo.health", HEA, "Period & pregnancy tracking app", "Freemium subscription",
      10, "Women want reliable cycle tracking and health insights.", note="Founded in Minsk; very large",
      aud="B2C", d=2, c=4, x=4, r=3, mo=1),

    # ---------------------------------------------------------------- Poland
    m("LiveChat (Text)", "Poland", "https://www.livechat.com", DEV, "Live chat for websites", "Subscription per agent",
      20, "Websites lose visitors who have unanswered questions.", note="Public (Text S.A.), bootstrapped origins",
      d=3, c=4, x=3, mo=1, comps=[("Smartsupp", "https://www.smartsupp.com", "Czech live chat", True)]),
    m("Brand24", "Poland", "https://brand24.com", MKT, "Social media & web mention monitoring",
      "Subscription SaaS", 99, "Brands miss what people say about them online.", note="Public (Warsaw)",
      sam=3_000, d=3, c=3, x=4, mo=3,
      comps=[("Mediaboard", "", "Czech media monitoring", True)]),
    m("Tidio", "Poland", "https://www.tidio.com", AI, "Live chat + AI support bot for small e-shops",
      "Freemium subscription", 29, "Small e-shops can't answer questions 24/7.", note=VC, d=4, c=4, x=3, mo=2,
      cogs=0.1, comps=[("Smartsupp", "https://www.smartsupp.com", "Czech live chat with AI", True)]),
    m("Booksy", "Poland", "https://booksy.com", LOC, "Booking app & marketplace for barbers and salons",
      "Subscription SaaS", 30, "Barbers take bookings by phone while cutting hair.", note=VC, d=3, c=5, x=3, mo=1,
      comps=[("Reservio", "https://www.reservio.cz", "Czech booking leader", True)]),
    m("Packhelp", "Poland", "https://packhelp.com", ECOM, "Custom-printed packaging for small brands",
      "Product sales", 200, "Small brands can't order branded boxes in low volumes.", note=VC, czk=4_000,
      sam=8_000, d=3, c=2, x=4, mo=2, cogs=0.55),
    m("BaseLinker (Base)", "Poland", "https://base.com", ECOM, "Order & marketplace management for online sellers",
      "Subscription by orders", 40, "Sellers juggle orders across shops and marketplaces.", note="Acquired by Cinven",
      d=4, c=3, x=4, mo=2, comps=[("Mergado", "https://www.mergado.com", "Czech feed & marketplace tools", True)]),
    m("inFakt", "Poland", "https://www.infakt.pl", FIN, "Online accounting office for sole traders",
      "Monthly subscription", 50, "Freelancers want software plus an accountant in one price.", note="Polish leader",
      czk=1_200, d=3, c=3, x=3, r=3, mo=3),
    m("ElevenLabs", "Poland", "https://elevenlabs.io", AI, "Realistic AI voice generation", "Freemium subscription",
      22, "Voice-overs and dubbing are slow and expensive.", note="Founded by Poles; HQ in the US/UK", d=3, c=3, x=5,
      mo=2, cogs=0.3),
    m("Brainly", "Poland", "https://brainly.com", EDU, "Homework-help Q&A community with AI", "Freemium subscription",
      10, "Students get stuck on homework.", note=VC, aud="B2C", czk=149, d=3, c=3, x=4, mo=3),
    m("Tylko", "Poland", "https://tylko.com", D2C, "Configurable made-to-measure furniture online",
      "Product sales", 700, "Standard furniture doesn't fit awkward spaces.", note=VC, aud="B2C", czk=15_000,
      sam=10_000, d=2, c=2, x=5, mo=2, cogs=0.55),
    m("Screen Studio", "Poland", "https://www.screen.studio", CRE, "Beautiful screen recordings for Mac",
      "One-time / subscription", 20, "Product demos look amateurish.", note="Solo-founder bootstrapped", d=2, c=3, x=4, mo=1),
    m("CleanShot X", "Poland", "https://cleanshot.com", DEV, "Screenshot & screen-recording app for Mac",
      "One-time + cloud subscription", 8, "Built-in screenshot tools are limited.", note="Small bootstrapped team",
      aud="B2C", d=1, c=4, x=3, mo=1),

    # ---------------------------------------------------------------- Baltics
    m("Pipedrive", "Estonia", "https://www.pipedrive.com", MKT, "Visual sales pipeline CRM", "Subscription per user",
      24, "Small sales teams lose deals in spreadsheets.", note="Founded in Tallinn; very large",
      d=3, c=4, x=4, mo=1, comps=[("Raynet", "https://raynet.cz", "Czech CRM", True)]),
    m("Katana", "Estonia", "https://katanamrp.com", FIN, "Cloud MRP for small manufacturers", "Subscription SaaS",
      179, "Small manufacturers track production in spreadsheets.", note=VC, sam=8_000, d=3, c=2, x=4, mo=2,
      segs=["Small food & drink producers", "Furniture workshops", "Cosmetics makers"]),
    m("Lingvist", "Estonia", "https://lingvist.com", EDU, "AI-driven vocabulary learning", "Consumer subscription",
      10, "Learners forget vocabulary fast.", note=VC, aud="B2C", d=2, c=4, x=4, mo=1),
    m("Omnisend", "Lithuania", "https://www.omnisend.com", ECOM, "Email & SMS automation for e-commerce",
      "Subscription by contacts", 16, "E-shops need automated flows without complexity.", note="Profitable",
      d=3, c=4, x=4, mo=2, comps=[("Ecomail", "https://ecomail.cz", "Czech e-shop email", True)]),
    m("MailerLite", "Lithuania", "https://www.mailerlite.com", MKT, "Affordable email marketing", "Freemium subscription",
      10, "Small businesses need simple, cheap email marketing.", note="Bootstrapped for a decade", d=3, c=5, x=4, mo=1),
    m("Hostinger", "Lithuania", "https://www.hostinger.com", DEV, "Low-cost web hosting & website builder",
      "Annual subscription", 3, "Small sites need cheap, simple hosting.", note="Profitable, global", d=2, c=5, x=4, mo=1,
      comps=[("WEDOS", "https://www.wedos.cz", "Czech hosting leader", True), ("Forpsi", "https://www.forpsi.com", "Czech hosting", True)]),
    m("CGTrader", "Lithuania", "https://www.cgtrader.com", CRE, "Marketplace for 3D models", "Commission",
      50, "Designers and brands need 3D assets.", note=VC, sam=1_000, d=1, c=3, x=4, mo=1),
    m("Fractory", "Estonia", "https://fractory.com", COM, "Online marketplace for custom metal parts",
      "Margin on orders", 1000, "Engineers wait days for quotes from metal workshops.", note=VC, czk=20_000,
      sam=2_000, d=3, c=2, x=4, mo=3, cz="Czechia's large engineering sector has many small workshops with spare capacity."),
    m("Printful", "Latvia", "https://www.printful.com", CRE, "Print-on-demand fulfilment", "Margin on products",
      50, "Creators want merch without holding stock.", note="Profitable, global", d=3, c=3, x=4, mo=2, cogs=0.6),

    # ---------------------------------------------------------------- Slovakia & Hungary
    m("Slido", "Slovakia", "https://www.slido.com", DEV, "Live Q&A and polls for meetings & events",
      "Subscription SaaS", 12, "Audiences can't ask questions in large meetings.", note="Acquired by Cisco",
      d=3, c=3, x=3, mo=2),
    m("Mangools", "Slovakia", "https://mangools.com", MKT, "Beginner-friendly SEO tools (KWFinder)",
      "Subscription SaaS", 29, "SEO tools are too complex and expensive for beginners.", note="Bootstrapped",
      d=3, c=4, x=4, mo=2, comps=[("Collabim", "https://www.collabim.cz", "Czech SEO", True)]),
    m("Bookio", "Slovakia", "https://www.bookio.com", LOC, "Online booking for services & restaurants",
      "Subscription SaaS", 20, "Businesses need self-service online booking.", note="Slovak, active in CZ",
      d=3, c=5, x=3, mo=2),
    m("SuperFaktúra", "Slovakia", "https://www.superfaktura.sk", FIN, "Online invoicing", "Subscription SaaS",
      8, "Freelancers need simple compliant invoices.", note="Slovak market leader", d=3, c=5, x=3, r=3,
      comps=[("Fakturoid", "https://www.fakturoid.cz", "Czech market leader", True)]),
    m("Nicereply", "Slovakia", "https://www.nicereply.com", DEV, "Customer satisfaction surveys for support teams",
      "Subscription SaaS", 39, "Support teams don't measure customer happiness.", note=BOOT, sam=1_500, d=2, c=2, x=2, mo=1),
    m("Prezi", "Hungary", "https://prezi.com", DEV, "Zooming presentations & video overlays", "Freemium subscription",
      7, "Slide presentations are linear and dull.", note="Category pioneer", d=2, c=4, x=4, mo=1),
    m("Craft", "Hungary", "https://www.craft.do", DEV, "Beautiful docs & notes app", "Freemium subscription",
      8, "Documents look dull and are hard to organise.", note=VC, aud="B2C", d=2, c=4, x=4, mo=1),

    # ---------------------------------------------------------------- Romania & Balkans
    m("Planable", "Romania", "https://planable.io", MKT, "Social media content collaboration for agencies",
      "Subscription SaaS", 39, "Client approvals of social posts happen in email chaos.", note=VC, sam=3_000,
      d=3, c=3, x=3, mo=2),
    m("Photomath", "Croatia", "https://photomath.com", EDU, "Snap a maths problem, get step-by-step solution",
      "Freemium subscription", 10, "Students get stuck on maths homework.", note="Acquired by Google", aud="B2C",
      d=3, c=3, x=4, mo=2),
    m("Agrivi", "Croatia", "https://www.agrivi.com", DEV, "Farm management software", "Subscription SaaS",
      80, "Farmers track fields, costs and yields on paper.", note=VC, sam=10_000, d=2, c=2, x=4, r=2, mo=3,
      segs=["Mid-size farms", "Agricultural co-ops", "Vineyards in South Moravia"]),
    m("Databox", "Slovenia", "https://databox.com", MKT, "KPI dashboards from many data sources",
      "Freemium subscription", 59, "Teams can't see their key numbers in one place.", note=VC, sam=3_000,
      d=2, c=3, x=4, mo=1),

    # ---------------------------------------------------------------- Turkey & Israel
    m("Obilet", "Turkey", "https://www.obilet.com", HOS, "Bus & travel ticket comparison", "Commission",
      10, "Travellers compare bus companies on many sites.", note="Turkish market leader", aud="B2C",
      d=2, c=4, x=4, mo=1, comps=[("RegioJet / FlixBus sites", "", "Direct booking dominates in CZ", True)]),
    m("UserGuiding", "Turkey", "https://userguiding.com", DEV, "No-code product tours & onboarding",
      "Subscription SaaS", 89, "SaaS users churn because onboarding is confusing.", note=BOOT, sam=800, d=1, c=3, x=3, mo=1),
    m("Otsimo", "Turkey", "https://otsimo.com", EDU, "Educational apps for children with autism",
      "Consumer subscription", 15, "Families lack affordable special-education support.", note=VC, aud="B2C",
      czk=299, sam=10_000, d=3, c=1, x=4, r=2, mo=4),
    m("Fiverr", "Israel", "https://www.fiverr.com", COM, "Marketplace for freelance micro-services",
      "Commission", 50, "Small businesses need quick freelance help.", note="Public", czk=800, d=2, c=5, x=5, mo=1),
    m("Riverside", "Israel", "https://riverside.fm", CRE, "Studio-quality remote podcast & video recording",
      "Subscription SaaS", 19, "Remote interviews sound and look bad.", note=VC, d=2, c=3, x=4, mo=1),
    m("Guesty", "Israel", "https://www.guesty.com", HOS, "Property management platform for short-term rentals",
      "Subscription per listing", 30, "STR managers juggle channels, cleaning and messaging.", note=VC,
      czk=690, sam=5_000, d=3, c=3, x=4, r=3, mo=2),
    m("Cofix", "Israel", "https://www.cofix.co.il", HOS, "Fixed-price café chain (everything one price)",
      "Retail", 1000, "Coffee and snacks became too expensive for everyday buying.", note="Israeli chain",
      aud="B2C", czk=2_000, sam=30_000, d=2, c=3, x=4, r=2, mo=2, cogs=0.55),
    m("Tailor Brands", "Israel", "https://www.tailorbrands.com", AI, "AI logo, brand kit & business formation",
      "Subscription", 10, "New founders need a brand identity quickly.", note=VC, d=3, c=3, x=3, mo=2),
    m("Elementor", "Israel", "https://elementor.com", DEV, "Visual WordPress site builder", "Freemium + subscription",
      5, "WordPress sites are hard to design without code.", note="Profitable, very large", d=2, c=4, x=4, mo=1),

    # ---------------------------------------------------------------- Kazakhstan & Armenia
    m("Chocolife", "Kazakhstan", "https://chocolife.me", COM, "Daily deals for restaurants, spas & services",
      "Commission on vouchers", 20, "Local businesses need customers in quiet periods.", note="Kazakh market leader",
      czk=400, d=2, c=4, x=3, mo=2, comps=[("Slevomat", "https://www.slevomat.cz", "Czech deals leader", True)]),
    m("PicsArt", "Armenia", "https://picsart.com", CRE, "Mobile photo & video editor", "Freemium subscription",
      5, "Creators want easy editing on their phones.", note=VC, aud="B2C", d=2, c=4, x=4, mo=1),
    m("SoloLearn", "Armenia", "https://www.sololearn.com", EDU, "Learn-to-code mobile app", "Freemium subscription",
      13, "Beginners find coding intimidating.", note=VC, aud="B2C", d=2, c=4, x=4, mo=1),
    m("Krisp", "Armenia", "https://krisp.ai", AI, "AI noise cancellation & meeting notes", "Freemium subscription",
      8, "Background noise ruins calls.", note=VC, d=2, c=3, x=5, mo=1),
]
