"""Proven business models from Western & Northern Europe (UK, IE, DE, AT, CH, FR, Benelux, Nordics, South)."""

from ._helpers import AI, COM, CRE, D2C, DEV, ECOM, EDU, FIN, HEA, HOS, LOC, MKT, m

VC = "VC-backed; proves the category"
BOOT = "Bootstrapped and profitable; revenue not public"

MODELS = [
    # ---------------------------------------------------------------- United Kingdom
    m("FreeAgent", "UK", "https://www.freeagent.com", FIN, "Accounting for freelancers & micro-businesses",
      "Subscription SaaS", 30, "Freelancers dread bookkeeping and tax deadlines.", note="Acquired by NatWest",
      d=3, c=5, x=4, r=3, comps=[("Fakturoid", "https://www.fakturoid.cz", "Czech market leader", True)]),
    m("Paddle", "UK", "https://www.paddle.com", FIN, "Merchant of record for SaaS", "% of revenue", 100,
      "Software companies struggle with global sales tax and payments.", note=VC, sam=1_500, d=2, c=2, x=5, r=4, mo=1),
    m("GoCardless", "UK", "https://gocardless.com", FIN, "Recurring bank payments (direct debit)",
      "Per-transaction fee", 40, "Card payments fail and cost too much for recurring billing.", note=VC,
      d=3, c=3, x=5, r=4, mo=2, cz="Czech inkaso/SIPO and QR platba are the local rails to integrate."),
    m("Cleo", "UK", "https://web.meetcleo.com", FIN, "AI budgeting assistant with attitude", "Consumer subscription",
      6, "Young people struggle to manage money.", note=VC, aud="B2C", czk=129, d=2, c=3, x=4, r=3, mo=3),
    m("Farewill", "UK", "https://farewill.com", FIN, "Online wills, probate & funerals", "Per-service fee",
      150, "Writing a will feels expensive and intimidating.", note=VC, aud="B2C", czk=2_490, sam=15_000,
      d=3, c=2, x=3, r=4, mo=4, cz="Czech inheritance runs through notaries; a guided will (závěť) service is a gap."),
    m("Synthesia", "UK", "https://www.synthesia.io", AI, "AI video avatars for training videos", "Subscription SaaS",
      30, "Filming training videos is slow and expensive.", note=VC, d=3, c=3, x=5, mo=2, cogs=0.2),
    m("Juro", "UK", "https://juro.com", DEV, "Contract management for in-house teams", "Subscription SaaS",
      300, "Contracts get lost in email and Word versions.", note=VC, sam=2_000, d=2, c=3, x=4, r=2, mo=2,
      comps=[("Legito", "https://www.legito.com", "Czech document automation", True)]),
    m("Fixflo", "UK", "https://www.fixflo.com", FIN, "Repair reporting for property managers", "Subscription per unit",
      100, "Tenants report repairs by phone; managers lose track.", note=BOOT, czk=790, sam=6_000,
      d=3, c=2, x=3, mo=3, segs=["Property administrators (správcovské firmy)", "SVJ committees", "Landlords"]),
    m("Mumsnet", "UK", "https://www.mumsnet.com", COM, "Parenting forum & community", "Advertising",
      300, "Parents want honest peer advice.", note="Founder-owned for 20+ years", czk=5_000, sam=1_000,
      d=2, c=5, x=3, mo=2, comps=[("Modrý koník", "https://www.modrykonik.cz", "Czech parenting forum", True),
                                  ("eMimino", "https://www.emimino.cz", "Czech parenting portal", True)]),
    m("Carwow", "UK", "https://www.carwow.co.uk", COM, "Compare new-car offers from dealers", "Dealer fees",
      300, "Buying a car means haggling with many dealers.", note=VC, czk=5_000, sam=1_500, d=3, c=4, x=4, mo=2,
      comps=[("Sauto.cz", "https://www.sauto.cz", "Seznam car classifieds", True)]),
    m("WeBuyAnyCar", "UK", "https://www.webuyanycar.com", COM, "Instant online car valuation & purchase",
      "Margin on resale", 300, "Selling a used car privately is slow and risky.", note="Large, profitable",
      aud="B2C", czk=5_000, sam=10_000, d=3, c=4, x=5, r=3, mo=2,
      comps=[("AAA Auto", "https://www.aaaauto.cz", "Largest Czech used-car dealer", True)]),
    m("OpenRent", "UK", "https://www.openrent.co.uk", COM, "Landlord-direct letting platform", "Flat fees",
      50, "Letting agents charge high fees for little work.", note="Bootstrapped, profitable", czk=900,
      d=3, c=5, x=3, r=3, comps=[("Bezrealitky", "https://www.bezrealitky.cz", "Very similar Czech platform", True)]),
    m("Treatwell", "UK", "https://www.treatwell.co.uk", LOC, "Beauty & wellness booking marketplace",
      "Commission per booking", 60, "Customers can't book salons online.", note=VC, d=3, c=5, x=4, mo=1,
      comps=[("Reservio", "https://www.reservio.cz", "Czech booking leader", True)]),
    m("Moo", "UK", "https://www.moo.com", D2C, "Premium online printing (business cards)", "Product sales",
      40, "Small businesses want great print without a print shop.", note="Profitable, founder-led",
      czk=800, d=2, c=4, x=4, mo=1, cogs=0.45),
    m("Moonpig", "UK", "https://www.moonpig.com", D2C, "Personalised greeting cards & gifts online",
      "Product sales", 10, "Buying and posting cards is inconvenient.", note="Public", aud="B2C", czk=199,
      d=2, c=3, x=4, mo=2, cogs=0.45),
    m("Bloom & Wild", "UK", "https://www.bloomandwild.com", D2C, "Letterbox flower delivery & subscriptions",
      "Product + subscription", 40, "Flower delivery is expensive and unreliable.", note=VC, aud="B2C", czk=790,
      d=3, c=3, x=4, mo=2, cogs=0.5),
    m("Pact Coffee", "UK", "https://www.pactcoffee.com", D2C, "Freshly roasted coffee subscription", "Subscription",
      30, "Supermarket coffee is stale.", note="Profitable", aud="B2C", czk=590, d=3, c=4, x=3, mo=2, cogs=0.5,
      comps=[("Czech speciality roasters (e.g. Doubleshot, Nordbeans)", "", "Many offer subscriptions", True)]),
    m("Tails.com", "UK", "https://tails.com", D2C, "Tailor-made dog food subscription", "Subscription",
      50, "Owners don't know what to feed their dog.", note="Acquired by Nestlé Purina", aud="B2C", czk=990,
      d=3, c=3, x=4, r=2, mo=3, cogs=0.55),
    m("Beauty Pie", "UK", "https://www.beautypie.com", D2C, "Membership for luxury cosmetics at cost price",
      "Membership + product", 15, "Luxury cosmetics carry huge markups.", note=VC, aud="B2C", czk=390,
      d=2, c=4, x=4, mo=1, comps=[("Notino", "https://www.notino.cz", "Czech beauty e-commerce giant", True)]),
    m("Gymshark", "UK", "https://www.gymshark.com", D2C, "Fitness apparel built via influencers", "Product sales",
      60, "Gym-goers want stylish performance wear.", note="Bootstrapped to $1B+ valuation", aud="B2C",
      czk=1_200, d=2, c=4, x=3, mo=2, cogs=0.45),
    m("Huel", "UK", "https://huel.com", D2C, "Nutritionally complete food", "Product + subscription",
      60, "Busy people eat unhealthily on the go.", note="Profitable, founder-led", aud="B2C", czk=1_200,
      d=2, c=3, x=3, r=3, mo=2, cogs=0.5),
    m("Patch Plants", "UK", "https://www.patchplants.com", D2C, "Houseplant delivery for city flats",
      "Product sales", 40, "Urban renters don't know which plants survive indoors.", note=VC, aud="B2C", czk=700,
      d=2, c=3, x=4, mo=2, cogs=0.5),
    m("Wild", "UK", "https://www.wearewild.com", D2C, "Refillable natural deodorant subscription",
      "Subscription", 10, "Plastic-free personal care is hard to find.", note="Acquired by Unilever",
      aud="B2C", czk=249, d=2, c=3, x=3, mo=2, cogs=0.45),
    m("Smol", "UK", "https://smolproducts.com", D2C, "Eco laundry capsules by subscription", "Subscription",
      8, "Big-brand detergents are overpriced and plastic-heavy.", note=VC, aud="B2C", czk=199,
      d=3, c=3, x=3, mo=2, cogs=0.5),
    m("Olio", "UK", "https://olioapp.com", COM, "Neighbour food-sharing app", "Freemium + business partnerships",
      20, "Surplus food gets binned instead of shared.", note=VC, aud="B2C", d=2, c=2, x=3, r=2, mo=2),
    m("Thriva", "UK", "https://thriva.co", HEA, "At-home blood tests with doctor-reviewed results",
      "Per-test + subscription", 40, "Getting a health check requires a GP visit.", note=VC, aud="B2C", czk=990,
      d=3, c=3, x=4, r=4, mo=3, comps=[("Private lab networks", "", "Pay-per-test without referral (verify)", True)]),
    m("Lottie", "UK", "https://lottie.org", HEA, "Care-home search & matching", "Commission from care homes",
      200, "Families struggle to find and compare care homes.", note=VC, czk=4_000, sam=2_000, d=3, c=2, x=3, r=3, mo=4,
      cz="Czech seniors' homes (domovy pro seniory) have long waiting lists - capacity search is the pain."),
    m("Birdie", "UK", "https://www.birdie.care", HEA, "Software for home-care agencies", "Subscription per client",
      200, "Home-care agencies run visits and care notes on paper.", note=VC, czk=4_000, sam=2_000,
      d=3, c=2, x=4, r=3, mo=3),
    m("Seneca Learning", "UK", "https://senecalearning.com", EDU, "Free adaptive revision for school exams",
      "Freemium + premium", 8, "Students revise inefficiently for exams.", note=VC, aud="B2C", czk=149,
      d=4, c=3, x=3, mo=5, comps=[("Umíme to", "https://www.umimeto.org", "Czech adaptive practice", True)]),
    m("Twinkl", "UK", "https://www.twinkl.co.uk", EDU, "Teaching resources subscription", "Subscription",
      10, "Teachers spend evenings creating worksheets.", note="Bootstrapped to hundreds of employees",
      aud="B2C", czk=199, sam=60_000, d=4, c=3, x=3, mo=4, cz="Materials must follow the Czech RVP curriculum."),
    m("Zen Educate", "UK", "https://www.zeneducate.com", EDU, "Marketplace for supply teachers", "Margin on placements",
      500, "Schools can't find cover teachers at short notice.", note=VC, czk=8_000, sam=3_000,
      d=3, c=2, x=3, r=3, mo=3),

    # ---------------------------------------------------------------- Ireland
    m("Flipdish", "Ireland", "https://www.flipdish.com", HOS, "Branded online ordering apps for takeaways",
      "Subscription + per-order", 80, "Restaurants lose 25-30% to delivery platforms.", note=VC, czk=1_490,
      d=4, c=3, x=4, mo=2, comps=[("Wolt / Foodora / Bolt Food", "", "Commission-heavy aggregators", False)]),
    m("Teamwork", "Ireland", "https://www.teamwork.com", DEV, "Project management for client-service agencies",
      "Subscription per user", 14, "Agencies lose profit on untracked client work.", note="Bootstrapped for 15+ years",
      d=2, c=4, x=3, mo=1, comps=[("Costlocker", "https://www.costlocker.com", "Czech agency tool", True)]),
    m("Glofox", "Ireland", "https://www.glofox.com", HEA, "Gym & studio management software", "Subscription SaaS",
      110, "Boutique gyms manage members and classes in several tools.", note="Acquired by ABC Fitness",
      sam=3_000, d=3, c=4, x=3, mo=2),

    # ---------------------------------------------------------------- Germany / Austria / Switzerland
    m("sevDesk", "Germany", "https://sevdesk.de", FIN, "Cloud accounting for small businesses", "Subscription SaaS",
      20, "Small firms find bookkeeping and tax filing painful.", note=VC, d=3, c=5, x=4, r=3),
    m("Softr", "Germany", "https://www.softr.io", DEV, "No-code apps & portals on Airtable/Sheets",
      "Subscription SaaS", 60, "Teams need client portals without developers.", note=VC, sam=3_000, d=2, c=3, x=4, mo=1),
    m("n8n", "Germany", "https://n8n.io", DEV, "Fair-code workflow automation", "Cloud subscription + self-host",
      24, "Teams want Zapier-like automation they can self-host.", note=VC, sam=3_000, d=2, c=3, x=5, mo=1),
    m("Things (Cultured Code)", "Germany", "https://culturedcode.com", DEV, "Premium to-do app for Apple devices",
      "One-time purchase", 50, "People want a calm, well-designed task manager.", note="Small bootstrapped team",
      aud="B2C", d=1, c=4, x=4, mo=1),
    m("HelloFresh", "Germany", "https://www.hellofresh.com", D2C, "Meal-kit subscription", "Weekly subscription",
      240, "Families struggle to plan and shop for dinners.", note="Public", aud="B2C", czk=3_500, sam=20_000,
      d=2, c=4, x=5, r=3, mo=2, cogs=0.6,
      comps=[("Rohlík.cz", "https://www.rohlik.cz", "Online grocery with recipe boxes", True)]),
    m("mymuesli", "Germany", "https://www.mymuesli.com", D2C, "Custom-mix muesli online", "Product sales",
      20, "Supermarket cereals are generic and sugary.", note="Bootstrapped by three students", aud="B2C", czk=390,
      d=2, c=2, x=3, r=2, mo=2, cogs=0.5),
    m("Grover", "Germany", "https://www.grover.com", COM, "Rent-a-tech subscriptions", "Monthly rental",
      40, "Buying electronics outright is expensive and wasteful.", note=VC, aud="B2C", czk=800,
      d=3, c=2, x=5, r=3, mo=2, cogs=0.6),
    m("Taxfix", "Germany", "https://taxfix.de", FIN, "Mobile tax returns for employees", "Fee per return",
      40, "Employees skip tax refunds because forms are confusing.", note=VC, aud="B2C", czk=99, sam=100_000,
      d=2, c=3, x=4, r=4, mo=4,
      comps=[("Portál MOJE daně", "https://adisspr.mfcr.cz", "Official free filing", True)],
      cz="Many Czech employees let employers file (roční zúčtování); ~99 CZK/month equivalent pricing."),
    m("Komoot", "Germany", "https://www.komoot.com", COM, "Outdoor route planning & navigation",
      "Map-region purchases + subscription", 5, "Hikers and cyclists need reliable routes.", note="Bootstrapped-first",
      aud="B2C", d=2, c=5, x=5, mo=1, comps=[("Mapy.com", "https://mapy.com", "Seznam maps, dominant outdoors in CZ", True)]),
    m("Zenjob", "Germany", "https://www.zenjob.com", COM, "On-demand student jobs platform", "Margin on hours",
      800, "Businesses need flexible staff; students want flexible shifts.", note=VC, czk=12_000, sam=3_000,
      d=4, c=3, x=4, r=4, mo=3, cz="Czech brigády culture and DPP contracts fit the model; labour-agency licence needed."),
    m("Blinkist", "Germany", "https://www.blinkist.com", EDU, "15-minute book summaries", "Consumer subscription",
      12, "Busy people don't have time to read non-fiction.", note=VC, aud="B2C", d=2, c=3, x=3, mo=2),
    m("Babbel", "Germany", "https://www.babbel.com", EDU, "Language-learning app", "Consumer subscription",
      13, "Adults want practical conversation skills.", note="Profitable, large", aud="B2C", d=3, c=5, x=5, mo=1),
    m("Freeletics", "Germany", "https://www.freeletics.com", HEA, "AI bodyweight fitness coach", "Consumer subscription",
      12, "People want effective workouts without a gym.", note=VC, aud="B2C", d=2, c=4, x=4, mo=1),
    m("Tandem", "Germany", "https://tandem.net", EDU, "Language-exchange app", "Freemium subscription",
      10, "Learners can't find native speakers to practise with.", note=VC, aud="B2C", d=2, c=3, x=4, mo=2),
    m("Makerist", "Germany", "https://www.makerist.de", CRE, "Sewing & craft patterns and courses marketplace",
      "Commission + courses", 10, "Crafters want patterns and video guidance.", note=VC, aud="B2C",
      d=2, c=2, x=3, mo=3),
    m("remove.bg", "Austria", "https://www.remove.bg", AI, "One-click image background removal",
      "Credits + subscription", 9, "Cutting out images manually is tedious.", note="Bootstrapped, acquired by Canva",
      d=3, c=4, x=4, mo=1, cogs=0.1),
    m("Refurbed", "Austria", "https://www.refurbed.at", COM, "Marketplace for refurbished electronics",
      "Commission", 40, "New electronics are expensive and wasteful.", note=VC, aud="B2C", czk=500,
      d=3, c=3, x=4, r=2, mo=2),
    m("Tractive", "Austria", "https://tractive.com", D2C, "GPS pet trackers with subscription", "Device + subscription",
      8, "Owners panic when pets run away.", note="Bootstrapped-first", aud="B2C", czk=149, d=3, c=2, x=5, mo=2),
    m("PlanRadar", "Austria", "https://www.planradar.com", DEV, "Defect & task management for construction",
      "Subscription per user", 35, "Construction defects are tracked on paper and photos.", note=VC,
      sam=6_000, d=3, c=2, x=3, mo=3, segs=["Construction firms", "Developers", "Facility managers"]),
    m("Smallpdf", "Switzerland", "https://smallpdf.com", DEV, "Online PDF tools", "Freemium subscription", 9,
      "People need to compress, convert and sign PDFs quickly.", note="Bootstrapped to tens of millions of users",
      aud="B2C", d=2, c=5, x=3, mo=1),
    m("Doodle", "Switzerland", "https://doodle.com", DEV, "Group scheduling polls", "Freemium subscription",
      7, "Finding a time for a group is chaotic.", note="Category benchmark", d=2, c=4, x=2, mo=1),
    m("Beekeeper", "Switzerland", "https://www.beekeeper.io", DEV, "Communication app for frontline workers",
      "Subscription per user", 5, "Factory and retail workers have no company email.", note=VC, czk=3_000,
      sam=2_000, d=2, c=2, x=4, mo=2),

    # ---------------------------------------------------------------- France
    m("Doctolib", "France", "https://www.doctolib.fr", HEA, "Online doctor booking & practice software",
      "Subscription per practitioner", 150, "Patients waste time phoning for appointments.", note=VC,
      czk=2_490, sam=15_000, d=4, c=3, x=5, r=4, mo=3),
    m("Crisp", "France", "https://crisp.chat", DEV, "Customer messaging & live chat", "Freemium subscription",
      45, "Small teams need chat, email and social inbox in one place.", note=BOOT, d=3, c=4, x=4, mo=1,
      comps=[("Smartsupp", "https://www.smartsupp.com", "Brno-based live chat", True)]),
    m("lemlist", "France", "https://www.lemlist.com", MKT, "Personalised cold email outreach",
      "Subscription per user", 59, "Cold emails get ignored.", note="Bootstrapped to eight-figure ARR (founder-reported)",
      d=2, c=3, x=3, r=2, mo=1),
    m("Hunter", "France", "https://hunter.io", MKT, "Find & verify professional email addresses",
      "Freemium subscription", 49, "Sales teams can't find the right contact.", note=BOOT, d=2, c=3, x=3, r=3, mo=1),
    m("ShipFast", "France", "https://shipfa.st", DEV, "Next.js boilerplate for launching SaaS fast",
      "One-time purchase", 199, "Indie hackers rebuild auth and payments for every project.",
      note="Solo founder (Marc Lou) with public revenue", sam=1_000, d=1, c=3, x=2, mo=1),
    m("Photoroom", "France", "https://www.photoroom.com", AI, "AI product photos for sellers", "Freemium subscription",
      13, "Small sellers can't afford product photography.", note=VC, d=4, c=3, x=4, mo=2, cogs=0.1,
      segs=["Vinted & Bazoš sellers", "Shoptet merchants", "Marketplace sellers"]),
    m("Gorgias", "France", "https://www.gorgias.com", ECOM, "Help desk built for e-commerce", "Subscription by tickets",
      60, "E-shop support agents switch between help desk and store admin.", note=VC, d=3, c=3, x=4, mo=2,
      comps=[("Supportbox", "https://supportbox.cz", "Czech help desk", True)]),
    m("Swile", "France", "https://www.swile.co", FIN, "Digital meal vouchers & employee benefits card",
      "Fees from employers & merchants", 5, "Paper meal vouchers are clunky.", note=VC, czk=100, sam=100_000,
      d=2, c=5, x=5, r=4, mo=2, comps=[("Pluxee / Edenred / Up", "", "Established Czech stravenky providers", True)]),
    m("Livestorm", "France", "https://livestorm.co", DEV, "Browser-based webinars & virtual events",
      "Subscription SaaS", 99, "Webinar software is clunky for attendees.", note=VC, sam=2_000, d=2, c=3, x=4, mo=1),
    m("Ornikar", "France", "https://www.ornikar.com", EDU, "Online driving school", "Per-package fees",
      60, "Traditional driving schools are expensive and slow.", note=VC, aud="B2C", czk=1_200, sam=30_000,
      d=3, c=3, x=4, r=4, mo=4, cz="Czech rules require a registered autoškola - partner model likely needed."),
    m("La Belle Assiette", "France", "https://www.labelleassiette.com", HOS, "Book a private chef at home",
      "Commission per booking", 100, "Hosting special dinners at home is stressful.", note=VC, aud="B2C",
      czk=1_500, sam=15_000, d=2, c=2, x=3, r=2, mo=2),
    m("Yuka", "France", "https://yuka.io", HEA, "Scan food & cosmetics for health impact", "Freemium subscription",
      2, "Shoppers can't decode ingredient labels.", note="Independent, no ads", aud="B2C", czk=49,
      d=3, c=3, x=4, mo=3, cz="Needs a Czech product database (EAN codes, Czech labels)."),
    m("Ulule", "France", "https://www.ulule.com", CRE, "Crowdfunding for creative projects", "Commission",
      100, "Creators need upfront funding and validation.", note="Profitable", czk=1_500, sam=3_000,
      d=2, c=4, x=4, r=2, comps=[("Hithit", "https://www.hithit.com", "Czech crowdfunding", True)]),
    m("Lalilo", "France", "https://lalilo.com", EDU, "AI reading practice for primary schools", "School licences",
      300, "Teachers can't give each child individual reading practice.", note="Acquired by Renaissance",
      czk=5_000, sam=4_000, d=3, c=2, x=4, mo=5),
    m("Ankorstore", "France", "https://www.ankorstore.com", ECOM, "Wholesale marketplace for independent retailers",
      "Commission from brands", 60, "Small brands and shops can't find each other.", note=VC,
      d=3, c=2, x=4, mo=2, segs=["Czech food & cosmetics brands", "Concept stores", "Gift shops"]),
    m("Cheerz", "France", "https://www.cheerz.com", D2C, "Photo printing from your phone", "Product sales",
      15, "Photos stay on phones and never get printed.", note="Acquired", aud="B2C", czk=299,
      d=2, c=4, x=4, mo=1, cogs=0.5),
    m("Wecasa", "France", "https://www.wecasa.fr", LOC, "Beauty & wellness professionals at home",
      "Commission per booking", 60, "Busy people want massages and haircuts at home.", note=VC, aud="B2C",
      czk=900, d=3, c=2, x=3, r=2, mo=2),
    m("OpenClassrooms", "France", "https://openclassrooms.com", EDU, "Online vocational degrees with mentoring",
      "Tuition / employer-paid", 300, "Career changers need job-ready qualifications.", note=VC, aud="B2C",
      czk=6_000, sam=10_000, d=3, c=4, x=4, r=3, mo=3,
      comps=[("Czechitas", "https://www.czechitas.cz", "Czech tech education non-profit", True),
             ("ENGETO", "https://engeto.cz", "Czech IT academy", True)]),
    m("Timeleft", "France", "https://timeleft.com", COM, "Dinners with strangers matched by algorithm",
      "Monthly ticket subscription", 20, "City dwellers are lonely and want new friends.", note=VC, aud="B2C",
      czk=390, sam=40_000, d=3, c=2, x=2, mo=2),

    # ---------------------------------------------------------------- Benelux
    m("Framer", "Netherlands", "https://www.framer.com", DEV, "Design-first website builder", "Subscription SaaS",
      15, "Designers want to publish sites without developers.", note=VC, d=2, c=4, x=5, mo=1),
    m("Simple Analytics", "Netherlands", "https://www.simpleanalytics.com", DEV, "Privacy-first web analytics",
      "Subscription SaaS", 15, "Site owners want GDPR-safe analytics.", note=BOOT, d=3, c=3, x=4, mo=2),
    m("WeTransfer", "Netherlands", "https://wetransfer.com", DEV, "Simple large-file transfer", "Freemium + ads",
      12, "Email can't send large files.", note="Category benchmark", d=2, c=4, x=4, mo=1),
    m("Catawiki", "Netherlands", "https://www.catawiki.com", COM, "Curated online auctions for collectibles",
      "Buyer & seller commissions", 50, "Collectors can't find trustworthy special-object auctions.", note=VC,
      czk=800, d=2, c=4, x=4, mo=2, comps=[("Aukro", "https://aukro.cz", "Czech auction marketplace", True)]),
    m("Swapfiets", "Netherlands", "https://swapfiets.nl", COM, "Bike subscription with free repairs",
      "Monthly subscription", 20, "Owning and maintaining a bike is a hassle.", note="Owned by Pon", aud="B2C",
      czk=390, sam=20_000, d=3, c=3, x=4, mo=2, cogs=0.5,
      comps=[("Rekola", "https://www.rekola.cz", "Prague bike sharing", True)]),
    m("Studocu", "Netherlands", "https://www.studocu.com", EDU, "Student-shared study notes platform",
      "Freemium subscription", 10, "Students struggle to find good study materials.", note=VC, aud="B2C",
      czk=149, d=3, c=2, x=3, r=2, mo=2),
    m("Scribbr", "Netherlands", "https://www.scribbr.com", EDU, "Thesis proofreading & plagiarism checks",
      "Per-service fees", 100, "Students worry about thesis quality and plagiarism.", note="Bootstrapped",
      aud="B2C", czk=1_500, sam=30_000, d=3, c=3, x=3, mo=4,
      comps=[("Theses.cz", "https://theses.cz", "Plagiarism system used by Czech universities", True)]),
    m("Withlocals", "Netherlands", "https://www.withlocals.com", HOS, "Private tours with local hosts",
      "Commission per booking", 60, "Tourists want authentic, personal experiences.", note=VC, czk=1_000,
      sam=2_000, d=3, c=4, x=3, mo=2),
    m("Teamleader", "Belgium", "https://www.teamleader.eu", DEV, "CRM, projects & invoicing for small firms",
      "Subscription SaaS", 50, "Small firms use separate tools for sales, projects and invoices.", note=VC,
      d=3, c=4, x=4, r=2, mo=2),
    m("Odoo", "Belgium", "https://www.odoo.com", DEV, "Open-source modular business apps (ERP)",
      "Subscription per user", 25, "SMBs outgrow spreadsheets but can't afford big ERPs.", note="Profitable, very large",
      d=3, c=4, x=5, r=2, mo=2),
    m("Deliverect", "Belgium", "https://www.deliverect.com", HOS, "Connects delivery platforms to restaurant POS",
      "Subscription per location", 80, "Restaurants juggle a tablet per delivery app.", note=VC, czk=1_490,
      d=4, c=3, x=4, mo=2, segs=["Restaurants on Wolt, Foodora and Bolt Food", "Dark kitchens", "Restaurant chains"]),

    # ---------------------------------------------------------------- Nordics
    m("Vivino", "Denmark", "https://www.vivino.com", COM, "Wine-label scanning app & marketplace", "Commission on wine sales",
      30, "Wine shoppers can't judge bottles on the shelf.", note=VC, aud="B2C", czk=500, d=2, c=3, x=4, r=3, mo=2),
    m("Trustpilot", "Denmark", "https://www.trustpilot.com", MKT, "Open online review platform", "Subscription for businesses",
      250, "Consumers want to know which businesses to trust.", note="Public", sam=5_000, d=2, c=5, x=4, mo=1,
      comps=[("Heureka Ověřeno zákazníky", "https://www.heureka.cz", "Dominant Czech trust badge", True)]),
    m("Planday", "Denmark", "https://www.planday.com", HOS, "Staff scheduling for hourly workers",
      "Subscription per employee", 4, "Rotas and time sheets are managed in spreadsheets.", note="Acquired by Xero",
      czk=990, d=4, c=2, x=3, r=3, mo=3),
    m("Supermetrics", "Finland", "https://supermetrics.com", MKT, "Marketing data connectors to Sheets/Looker",
      "Subscription SaaS", 100, "Marketers copy ad data manually for reports.", note="Bootstrapped to large scale",
      sam=3_000, d=3, c=3, x=4, mo=3, cz="Adding Seznam Sklik connectors would be the local wedge."),
    m("Oura", "Finland", "https://ouraring.com", HEA, "Smart ring with sleep & health subscription",
      "Device + subscription", 6, "People want to understand sleep and recovery.", note=VC, aud="B2C", czk=149,
      d=2, c=3, x=5, r=3, mo=1),
    m("Spond", "Norway", "https://www.spond.com", COM, "Free app for sports clubs & teams", "Payment fees + sponsors",
      20, "Club organisers chase attendance and fees via group chats.", note="Profitable",
      czk=300, sam=20_000, d=4, c=2, x=3, mo=3,
      segs=["Youth sports clubs", "Amateur football & hockey teams", "Sokol units"]),
    m("Kahoot!", "Norway", "https://kahoot.com", EDU, "Game-based quizzes for classrooms & companies",
      "Freemium subscription", 10, "Lessons and trainings are passive.", note="Category benchmark",
      d=3, c=3, x=4, mo=2),
    m("Scrimba", "Norway", "https://scrimba.com", EDU, "Interactive coding screencasts", "Consumer subscription",
      20, "Video coding courses are passive.", note="Bootstrapped-first", aud="B2C", d=2, c=3, x=4, mo=2),
    m("Lovable", "Sweden", "https://lovable.dev", AI, "AI app builder from prompts", "Subscription SaaS",
      25, "Non-developers can't build web apps.", note=VC, d=3, c=3, x=5, mo=1, cogs=0.3),
    m("Mentimeter", "Sweden", "https://www.mentimeter.com", DEV, "Interactive presentations & live polls",
      "Freemium subscription", 12, "Audiences zone out in presentations.", note="Profitable", d=3, c=4, x=3, mo=1,
      comps=[("Slido", "https://www.slido.com", "Slovak-born, widely used in CZ", False)]),
    m("Mynewsdesk", "Sweden", "https://www.mynewsdesk.com", MKT, "PR newsroom & press distribution",
      "Subscription SaaS", 300, "Companies struggle to reach journalists.", note="Profitable", sam=2_000,
      d=2, c=3, x=3, mo=3),
    m("Epidemic Sound", "Sweden", "https://www.epidemicsound.com", CRE, "Royalty-free music for creators",
      "Subscription", 15, "Creators get copyright strikes for using music.", note="Large, profitable",
      d=2, c=4, x=5, mo=1),

    # ---------------------------------------------------------------- Southern Europe & Malta / Greece
    m("Typeform", "Spain", "https://www.typeform.com", DEV, "Conversational forms & surveys", "Freemium subscription",
      29, "Standard forms have low completion rates.", note=VC, d=2, c=4, x=3, mo=1,
      comps=[("Survio", "https://www.survio.com", "Brno-based surveys", True)]),
    m("Factorial", "Spain", "https://factorialhr.com", DEV, "All-in-one HR for SMBs", "Subscription per employee",
      8, "SMB HR runs on paper and spreadsheets.", note=VC, czk=2_490, d=3, c=3, x=4, r=3, mo=3),
    m("Fever", "Spain", "https://feverup.com", CRE, "Event discovery & own-produced experiences",
      "Ticket commission", 30, "People struggle to find unique things to do in their city.", note=VC,
      czk=500, sam=5_000, d=3, c=4, x=4, mo=2, comps=[("GoOut", "https://goout.net", "Czech event discovery", True)]),
    m("Lodgify", "Spain", "https://www.lodgify.com", HOS, "Vacation-rental websites & booking engine",
      "Subscription SaaS", 30, "Holiday-home owners depend on Airbnb/Booking fees.", note=VC, czk=690,
      sam=8_000, d=3, c=3, x=3, r=2, mo=2),
    m("Domestika", "Spain", "https://www.domestika.org", EDU, "Creative online courses", "Per-course + subscription",
      15, "Creatives want to learn from practitioners.", note=VC, aud="B2C", d=2, c=3, x=3, mo=2),
    m("Lingokids", "Spain", "https://lingokids.com", EDU, "English-learning app for young children",
      "Consumer subscription", 15, "Parents want screen time to be educational.", note=VC, aud="B2C", czk=249,
      d=3, c=3, x=4, mo=2),
    m("Treedom", "Italy", "https://www.treedom.net", D2C, "Plant a tree online as a gift or CSR",
      "Per-tree sales", 30, "People and companies want tangible climate gifts.", note="B Corp, profitable",
      czk=500, d=2, c=2, x=3, mo=2),
    m("Hotjar", "Malta", "https://www.hotjar.com", DEV, "Heatmaps & session recordings", "Freemium subscription",
      39, "Site owners don't know why visitors leave.", note="Bootstrapped to large scale", d=3, c=3, x=4, mo=1,
      comps=[("Smartlook", "https://www.smartlook.com", "Czech-founded session recording", True)]),
    m("Workable", "Greece", "https://www.workable.com", DEV, "Recruiting software for SMBs", "Subscription SaaS",
      169, "SMBs hire from inboxes and spreadsheets.", note=VC, sam=6_000, d=3, c=4, x=3, r=2, mo=2,
      comps=[("Recruitis", "https://recruitis.io", "Czech ATS", True), ("Teamio", "https://www.teamio.com", "Czech ATS", True)]),
]
